// <auto-generated>
/*
 * Payments App API
 *
 * Board and manage the Adyen Payments App on your Android mobile devices. ## Authentication Each request to the Payments App API must be signed with an API key. [Generate your API key](https://docs.adyen.com/development-resources/api-credentials#generate-api-key) in the Customer Area and then set this key to the `X-API-Key` header value.  ## Versioning  Payments App API handles versioning as part of the endpoint URL. For example, to send a request to this version of the `/merchants/{merchantId}/generatePaymentsAppBoardingToken` endpoint, use:  ```text https://management-test.adyen.com/v1/merchants/{merchantId}/generatePaymentsAppBoardingToken ```  ## Going live  To access the live endpoints, you need an API key from your live Customer Area. Use this API key to make requests to:  ```text https://management-live.adyen.com/v{version} ```  
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Adyen.Core;
using Adyen.PaymentsApp.Client;

namespace Adyen.PaymentsApp.Models
{
    /// <summary>
    /// PaymentsAppDto.
    /// </summary>
    public partial class PaymentsAppDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentsAppDto" /> class.
        /// </summary>
        /// <param name="installationId">The unique identifier of the Payments App instance.</param>
        /// <param name="merchantAccountCode">The account code associated with the Payments App instance.</param>
        /// <param name="status">The status of the Payments App instance.</param>
        /// <param name="merchantStoreCode">The store code associated with the Payments App instance.</param>
        [JsonConstructor]
        public PaymentsAppDto(string installationId, string merchantAccountCode, string status, Option<string?> merchantStoreCode = default)
        {
            InstallationId = installationId;
            MerchantAccountCode = merchantAccountCode;
            Status = status;
            _MerchantStoreCodeOption = merchantStoreCode;
            OnCreated();
        }
        
        /// <summary>
        /// Best practice: Use the constructor to initialize your objects to understand which parameters are required/optional.
        /// </summary>
        public PaymentsAppDto()
        {
        }

        partial void OnCreated();

        /// <summary>
        /// The unique identifier of the Payments App instance.
        /// </summary>
        /// <value>The unique identifier of the Payments App instance.</value>
        [JsonPropertyName("installationId")]
        public string InstallationId { get; set; }

        /// <summary>
        /// The account code associated with the Payments App instance.
        /// </summary>
        /// <value>The account code associated with the Payments App instance.</value>
        [JsonPropertyName("merchantAccountCode")]
        public string MerchantAccountCode { get; set; }

        /// <summary>
        /// The status of the Payments App instance.
        /// </summary>
        /// <value>The status of the Payments App instance.</value>
        [JsonPropertyName("status")]
        public string Status { get; set; }

        /// <summary>
        /// This is used to track if an optional field is set. If set, <see cref="MerchantStoreCode"/> will be populated.
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> _MerchantStoreCodeOption { get; private set; }

        /// <summary>
        /// The store code associated with the Payments App instance.
        /// </summary>
        /// <value>The store code associated with the Payments App instance.</value>
        [JsonPropertyName("merchantStoreCode")]
        public string? MerchantStoreCode { get { return this._MerchantStoreCodeOption; } set { this._MerchantStoreCodeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PaymentsAppDto {\n");
            sb.Append("  InstallationId: ").Append(InstallationId).Append("\n");
            sb.Append("  MerchantAccountCode: ").Append(MerchantAccountCode).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  MerchantStoreCode: ").Append(MerchantStoreCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PaymentsAppDto" />
    /// </summary>
    public class PaymentsAppDtoJsonConverter : JsonConverter<PaymentsAppDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="PaymentsAppDto"/>.
        /// </summary>
        /// <param name="utf8JsonReader"><see cref="Utf8JsonReader"/>.</param>
        /// <param name="typeToConvert"><see cref="Type"/>.</param>
        /// <param name="jsonSerializerOptions">The <see cref="JsonSerializerOptions"/>, initialized from <see cref="HostConfiguration"/>.</param>
        /// <returns><see cref="PaymentsAppDto"/>.</returns>
        /// <exception cref="JsonException"></exception>
        public override PaymentsAppDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> installationId = default;
            Option<string?> merchantAccountCode = default;
            Option<string?> status = default;
            Option<string?> merchantStoreCode = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? jsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (jsonPropertyName)
                    {
                        case "installationId":
                            installationId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "merchantAccountCode":
                            merchantAccountCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "merchantStoreCode":
                            merchantStoreCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }
            
            if (!installationId.IsSet)
                throw new ArgumentException("Property is required for class PaymentsAppDto.", nameof(installationId));

            if (!merchantAccountCode.IsSet)
                throw new ArgumentException("Property is required for class PaymentsAppDto.", nameof(merchantAccountCode));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class PaymentsAppDto.", nameof(status));

            return new PaymentsAppDto(installationId.Value!, merchantAccountCode.Value!, status.Value!, merchantStoreCode);
        }

        /// <summary>
        /// Serializes a <see cref="PaymentsAppDto"/>.
        /// </summary>
        /// <param name="writer"><see cref="Utf8JsonWriter"/></param>
        /// <param name="paymentsAppDto"></param>
        /// <param name="jsonSerializerOptions"><see cref="JsonSerializerOptions"/></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PaymentsAppDto paymentsAppDto, JsonSerializerOptions jsonSerializerOptions)
        {
            
            writer.WriteStartObject();
            
            WriteProperties(writer, paymentsAppDto, jsonSerializerOptions);
            
            writer.WriteEndObject();
            
        }

        /// <summary>
        /// Serializes the properties of <see cref="PaymentsAppDto"/>.
        /// </summary>
        /// <param name="writer"><see cref="Utf8JsonWriter"/></param>
        /// <param name="paymentsAppDto"></param>
        /// <param name="jsonSerializerOptions"><see cref="JsonSerializerOptions"/></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PaymentsAppDto paymentsAppDto, JsonSerializerOptions jsonSerializerOptions)
        {
            
            if (paymentsAppDto.InstallationId != null)
                writer.WriteString("installationId", paymentsAppDto.InstallationId);

            if (paymentsAppDto.MerchantAccountCode != null)
                writer.WriteString("merchantAccountCode", paymentsAppDto.MerchantAccountCode);

            if (paymentsAppDto.Status != null)
                writer.WriteString("status", paymentsAppDto.Status);

            if (paymentsAppDto._MerchantStoreCodeOption.IsSet)
                if (paymentsAppDto.MerchantStoreCode != null)
                    writer.WriteString("merchantStoreCode", paymentsAppDto.MerchantStoreCode);
        }
    }
}
