language: csharp
dist: trusty
mono: none
dotnet: 2.0.0
install:
- dotnet restore
script:
- dotnet build /p:TargetFrameworks=netcoreapp2.0
- dotnet test Adyen.EcommLibrary.Test/Adyen.EcommLibrary.Test.csproj