/*
 * Capital API
 *
 * The Capital API provides endpoints for embedding Adyen Capital into your [marketplace](https://docs.adyen.com/platforms/capital) or [platform](https://docs.adyen.com/platforms/capital). With Capital, you can offer business financing to your users as grants. When a user receives a grant, they must repay the grant amount in a specified term, in addition to paying a fee for using this service.  With these endpoints, you can: - **Get available grant offers**: You can get the grant offers that are available for your users. Adyen configures the financing amount, the fee, and the repayment conditions for each offer. These configurations are based on proactive risk analyses that Adyen performs on your users. - **Make requests for grants**: When a user selects a grant offer, you can make a request for the grant on their behalf. - **Get information about your grant account**: Your grant account tracks the information of all grants in your marketplace or platform.  ## Authentication Each request made to the Capital API must be signed with an API key. Generate an API key in your Customer Area.  To connect to the API, add an `X-API-Key` header with the API key as the value, for example:   ``` curl -H \"Content-Type: application/json\" \\ -H \"X-API-Key: YOUR_API_KEY\" \\ ... ```  ## Roles and permissions To use the Capital API, your API credential must have the following roles: - **Balance_Platform_Capital_Configuration_Role** - **Balance_Platform_Capital_Grant_Initiation_Role**  Reach out to your Adyen contact to set up these roles. ## Going live When going live, generate an API key in your [live Customer Area](https://ca-live.adyen.com/ca). You can then use the API key to send requests to `https://balanceplatform-api-live.adyen.com/capital/v{version}`.  
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Net.Http;
using Microsoft.Extensions.DependencyInjection;
using Adyen.Capital.Services;
using Adyen.Capital.Client;
using Adyen.Capital.Models;
using Adyen.Capital.Extensions;
using Adyen.Core;
using Adyen.Core.Auth;
using Adyen.Core.Client;
using Adyen.Core.Options;
using Adyen.Core.Converters;

namespace Adyen.Capital.Client
{
    /// <summary>
    /// Provides hosting configuration for Capital
    /// </summary>
    public class HostConfiguration
    {
        private readonly IServiceCollection _services;
        private readonly JsonSerializerOptions _jsonOptions = new JsonSerializerOptions();
        private readonly AdyenOptions _adyenOptions = new AdyenOptions();

        /// <summary>
        /// Instantiates the HostConfiguration (custom JsonConverters, Events, HttpClient) with the necessary dependencies to communicate with the API.
        /// </summary>
        /// <param name="services"><see cref="IServiceCollection"/></param>
        public HostConfiguration(IServiceCollection services)
        {
            _services = services;
            if (_jsonOptions.Converters.FirstOrDefault(x => x.GetType() == typeof(JsonStringEnumConverter)) == null)
                _jsonOptions.Converters.Add(new JsonStringEnumConverter());
            if (_jsonOptions.Converters.FirstOrDefault(x => x.GetType() == typeof(DateTimeJsonConverter)) == null)
                _jsonOptions.Converters.Add(new DateTimeJsonConverter());
            if (_jsonOptions.Converters.FirstOrDefault(x => x.GetType() == typeof(DateTimeNullableJsonConverter)) == null)
                _jsonOptions.Converters.Add(new DateTimeNullableJsonConverter());
            if (_jsonOptions.Converters.FirstOrDefault(x => x.GetType() == typeof(ByteArrayConverter)) == null)
                _jsonOptions.Converters.Add(new ByteArrayConverter());
            if (_jsonOptions.Converters.FirstOrDefault(x => x.GetType() == typeof(DateOnlyJsonConverter)) == null)
                _jsonOptions.Converters.Add(new DateOnlyJsonConverter());
            if (_jsonOptions.Converters.FirstOrDefault(x => x.GetType() == typeof(DateOnlyNullableJsonConverter)) == null)
                _jsonOptions.Converters.Add(new DateOnlyNullableJsonConverter());
            _jsonOptions.Converters.Add(new AULocalAccountIdentificationJsonConverter());
            _jsonOptions.Converters.Add(new ActionJsonConverter());
            _jsonOptions.Converters.Add(new AdditionalBankIdentificationJsonConverter());
            _jsonOptions.Converters.Add(new AdditionalBankIdentificationTypesJsonConverter());
            _jsonOptions.Converters.Add(new AdditionalBankIdentificationTypesNullableJsonConverter());
            _jsonOptions.Converters.Add(new AmountJsonConverter());
            _jsonOptions.Converters.Add(new BRLocalAccountIdentificationJsonConverter());
            _jsonOptions.Converters.Add(new BalanceJsonConverter());
            _jsonOptions.Converters.Add(new BankAccountIdentificationJsonConverter());
            _jsonOptions.Converters.Add(new CALocalAccountIdentificationJsonConverter());
            _jsonOptions.Converters.Add(new CALocalBankAccountTypeJsonConverter());
            _jsonOptions.Converters.Add(new CALocalBankAccountTypeNullableJsonConverter());
            _jsonOptions.Converters.Add(new CZLocalAccountIdentificationJsonConverter());
            _jsonOptions.Converters.Add(new DKLocalAccountIdentificationJsonConverter());
            _jsonOptions.Converters.Add(new DefaultErrorResponseEntityJsonConverter());
            _jsonOptions.Converters.Add(new DisbursementJsonConverter());
            _jsonOptions.Converters.Add(new DisbursementInfoUpdateJsonConverter());
            _jsonOptions.Converters.Add(new DisbursementRepaymentJsonConverter());
            _jsonOptions.Converters.Add(new DisbursementRepaymentInfoUpdateJsonConverter());
            _jsonOptions.Converters.Add(new DisbursementsJsonConverter());
            _jsonOptions.Converters.Add(new FeeJsonConverter());
            _jsonOptions.Converters.Add(new FundsCollectionJsonConverter());
            _jsonOptions.Converters.Add(new FundsCollectionTypeJsonConverter());
            _jsonOptions.Converters.Add(new FundsCollectionTypeNullableJsonConverter());
            _jsonOptions.Converters.Add(new GrantJsonConverter());
            _jsonOptions.Converters.Add(new GrantAccountJsonConverter());
            _jsonOptions.Converters.Add(new GrantCounterpartyJsonConverter());
            _jsonOptions.Converters.Add(new GrantInfoJsonConverter());
            _jsonOptions.Converters.Add(new GrantInfoCounterpartyJsonConverter());
            _jsonOptions.Converters.Add(new GrantLimitJsonConverter());
            _jsonOptions.Converters.Add(new GrantOfferJsonConverter());
            _jsonOptions.Converters.Add(new GrantOfferFeeJsonConverter());
            _jsonOptions.Converters.Add(new GrantOffersJsonConverter());
            _jsonOptions.Converters.Add(new GrantsJsonConverter());
            _jsonOptions.Converters.Add(new HKLocalAccountIdentificationJsonConverter());
            _jsonOptions.Converters.Add(new HULocalAccountIdentificationJsonConverter());
            _jsonOptions.Converters.Add(new IbanAccountIdentificationJsonConverter());
            _jsonOptions.Converters.Add(new InvalidFieldJsonConverter());
            _jsonOptions.Converters.Add(new NOLocalAccountIdentificationJsonConverter());
            _jsonOptions.Converters.Add(new NZLocalAccountIdentificationJsonConverter());
            _jsonOptions.Converters.Add(new NumberAndBicAccountIdentificationJsonConverter());
            _jsonOptions.Converters.Add(new PLLocalAccountIdentificationJsonConverter());
            _jsonOptions.Converters.Add(new RepaymentJsonConverter());
            _jsonOptions.Converters.Add(new RepaymentTermJsonConverter());
            _jsonOptions.Converters.Add(new SELocalAccountIdentificationJsonConverter());
            _jsonOptions.Converters.Add(new SGLocalAccountIdentificationJsonConverter());
            _jsonOptions.Converters.Add(new StatusJsonConverter());
            _jsonOptions.Converters.Add(new ThresholdRepaymentJsonConverter());
            _jsonOptions.Converters.Add(new UKLocalAccountIdentificationJsonConverter());
            _jsonOptions.Converters.Add(new USLocalAccountIdentificationJsonConverter());
            _jsonOptions.Converters.Add(new USLocalBankAccountTypeJsonConverter());
            _jsonOptions.Converters.Add(new USLocalBankAccountTypeNullableJsonConverter());
            JsonSerializerOptionsProvider jsonSerializerOptionsProvider = new(_jsonOptions);
            _services.AddSingleton(jsonSerializerOptionsProvider);
        }

        /// <summary>
        /// Configures the <see cref="JsonSerializerOptions"/>.
        /// </summary>
        /// <param name="jsonSerializerOptions">Configures the <see cref="JsonSerializerOptions"/>.</param>
        /// <returns><see cref="HostConfiguration"/>.</returns>
        public HostConfiguration ConfigureJsonOptions(Action<JsonSerializerOptions> jsonSerializerOptions)
        {
            jsonSerializerOptions(_jsonOptions);
            return this;
        }

        /// <summary>
        /// Configures the <see cref="AdyenOptions"/> (e.g. Environment, LiveEndpointPrefix, <see cref="ITokenProvider{ApiKeyToken}"/>).
        /// </summary>
        /// <param name="adyenOptions">Configures the <see cref="AdyenOptions"/>.</param>
        /// <returns><see cref="HostConfiguration"/>.</returns>
        public HostConfiguration ConfigureAdyenOptions(Action<AdyenOptions> adyenOptions)
        {
            adyenOptions(_adyenOptions);
            _services.AddSingleton(new AdyenOptionsProvider(_adyenOptions));
            _services.AddSingleton<ITokenProvider<ApiKeyToken>>(new TokenProvider<ApiKeyToken>(new ApiKeyToken(_adyenOptions.AdyenApiKey, ClientUtils.ApiKeyHeader.X_API_Key, "")));
                    
            return this;
        }
    }
}
