// <auto-generated>
/*
 * Transaction webhooks
 *
 * After a transfer is booked in a balance account, Adyen sends webhooks with information about the transaction.  You can use the data from these webhooks to, for example: - Update balances in your dashboards. - Keep track of incoming and outgoing funds.
 *
 * The version of the OpenAPI document: 4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Adyen.Core;
using Adyen.TransactionWebhooks.Client;

namespace Adyen.TransactionWebhooks.Models
{
    /// <summary>
    /// PlatformPayment.
    /// </summary>
    public partial class PlatformPayment : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlatformPayment" /> class.
        /// </summary>
        /// <param name="modificationMerchantReference">The capture&#39;s merchant reference included in the transfer.</param>
        /// <param name="modificationPspReference">The capture reference included in the transfer.</param>
        /// <param name="paymentMerchantReference">The payment&#39;s merchant reference included in the transfer.</param>
        /// <param name="platformPaymentType">Specifies the nature of the transfer. This parameter helps categorize transfers so you can reconcile transactions at a later time, using the Balance Platform Accounting Report for [marketplaces](https://docs.adyen.com/marketplaces/reports-and-fees/balance-platform-accounting-report/) or [platforms](https://docs.adyen.com/platforms/reports-and-fees/balance-platform-accounting-report/).  Possible values:  * **AcquiringFees**: the acquiring fee (the aggregated amount of interchange and scheme fee) incurred on a transaction.  * **AdyenCommission**: the transaction fee due to Adyen under [blended rates](https://www.adyen.com/knowledge-hub/guides/payments-training-guide/get-the-best-from-your-card-processing).  * **AdyenFees**: all transaction fees due to Adyen. This is the aggregated amount of Adyen&#39;s commission and markup.  * **AdyenMarkup**: the transaction fee due to Adyen under [Interchange++ pricing](https://www.adyen.com/pricing).  * **BalanceAccount**: the amount booked to your user after the deduction of the relevant fees.  * **Commission**: your platform&#39;s or marketplace&#39;s commission on a transaction.  * **DCCPlatformCommission**: the Dynamic Currency Conversion (DCC) fee on a transaction.  * **Interchange**: the interchange fee (fee paid to the issuer) incurred on a transaction.  * **PaymentFee**: the aggregated amount of all transaction fees.  * **Remainder**: the leftover amount after currency conversion.  * **SchemeFee**: the scheme fee incurred on a transaction.  * **Surcharge**: the surcharge paid by the customer on a transaction.  * **Tip**: the tip paid by the customer.  * **TopUp**: an incoming transfer to top up your user&#39;s balance account.  * **VAT**: the value-added tax charged on the payment.</param>
        /// <param name="pspPaymentReference">The payment reference included in the transfer.</param>
        /// <param name="type">**platformPayment** (default to TypeEnum.PlatformPayment)</param>
        [JsonConstructor]
        public PlatformPayment(Option<string?> modificationMerchantReference = default, Option<string?> modificationPspReference = default, Option<string?> paymentMerchantReference = default, Option<PlatformPaymentTypeEnum?> platformPaymentType = default, Option<string?> pspPaymentReference = default, Option<TypeEnum?> type = default)
        {
            _ModificationMerchantReferenceOption = modificationMerchantReference;
            _ModificationPspReferenceOption = modificationPspReference;
            _PaymentMerchantReferenceOption = paymentMerchantReference;
            _PlatformPaymentTypeOption = platformPaymentType;
            _PspPaymentReferenceOption = pspPaymentReference;
            _TypeOption = type;
            OnCreated();
        }
        
        /// <summary>
        /// Best practice: Use the constructor to initialize your objects to understand which parameters are required/optional.
        /// </summary>
        public PlatformPayment()
        {
        }

        partial void OnCreated();

        /// <summary>
        /// Specifies the nature of the transfer. This parameter helps categorize transfers so you can reconcile transactions at a later time, using the Balance Platform Accounting Report for [marketplaces](https://docs.adyen.com/marketplaces/reports-and-fees/balance-platform-accounting-report/) or [platforms](https://docs.adyen.com/platforms/reports-and-fees/balance-platform-accounting-report/).  Possible values:  * **AcquiringFees**: the acquiring fee (the aggregated amount of interchange and scheme fee) incurred on a transaction.  * **AdyenCommission**: the transaction fee due to Adyen under [blended rates](https://www.adyen.com/knowledge-hub/guides/payments-training-guide/get-the-best-from-your-card-processing).  * **AdyenFees**: all transaction fees due to Adyen. This is the aggregated amount of Adyen's commission and markup.  * **AdyenMarkup**: the transaction fee due to Adyen under [Interchange++ pricing](https://www.adyen.com/pricing).  * **BalanceAccount**: the amount booked to your user after the deduction of the relevant fees.  * **Commission**: your platform's or marketplace's commission on a transaction.  * **DCCPlatformCommission**: the Dynamic Currency Conversion (DCC) fee on a transaction.  * **Interchange**: the interchange fee (fee paid to the issuer) incurred on a transaction.  * **PaymentFee**: the aggregated amount of all transaction fees.  * **Remainder**: the leftover amount after currency conversion.  * **SchemeFee**: the scheme fee incurred on a transaction.  * **Surcharge**: the surcharge paid by the customer on a transaction.  * **Tip**: the tip paid by the customer.  * **TopUp**: an incoming transfer to top up your user's balance account.  * **VAT**: the value-added tax charged on the payment.
        /// </summary>
        /// <value>Specifies the nature of the transfer. This parameter helps categorize transfers so you can reconcile transactions at a later time, using the Balance Platform Accounting Report for [marketplaces](https://docs.adyen.com/marketplaces/reports-and-fees/balance-platform-accounting-report/) or [platforms](https://docs.adyen.com/platforms/reports-and-fees/balance-platform-accounting-report/).  Possible values:  * **AcquiringFees**: the acquiring fee (the aggregated amount of interchange and scheme fee) incurred on a transaction.  * **AdyenCommission**: the transaction fee due to Adyen under [blended rates](https://www.adyen.com/knowledge-hub/guides/payments-training-guide/get-the-best-from-your-card-processing).  * **AdyenFees**: all transaction fees due to Adyen. This is the aggregated amount of Adyen&#39;s commission and markup.  * **AdyenMarkup**: the transaction fee due to Adyen under [Interchange++ pricing](https://www.adyen.com/pricing).  * **BalanceAccount**: the amount booked to your user after the deduction of the relevant fees.  * **Commission**: your platform&#39;s or marketplace&#39;s commission on a transaction.  * **DCCPlatformCommission**: the Dynamic Currency Conversion (DCC) fee on a transaction.  * **Interchange**: the interchange fee (fee paid to the issuer) incurred on a transaction.  * **PaymentFee**: the aggregated amount of all transaction fees.  * **Remainder**: the leftover amount after currency conversion.  * **SchemeFee**: the scheme fee incurred on a transaction.  * **Surcharge**: the surcharge paid by the customer on a transaction.  * **Tip**: the tip paid by the customer.  * **TopUp**: an incoming transfer to top up your user&#39;s balance account.  * **VAT**: the value-added tax charged on the payment.</value>
        [JsonConverter(typeof(PlatformPaymentTypeEnumJsonConverter))]
        public class PlatformPaymentTypeEnum : IEnum
        {
            /// <summary>
            /// Returns the value of the PlatformPaymentTypeEnum.
            /// </summary>
            public string? Value { get; set; }

            /// <summary>
            /// PlatformPaymentTypeEnum.AcquiringFees - AcquiringFees
            /// </summary>
            public static readonly PlatformPaymentTypeEnum AcquiringFees = new("AcquiringFees");

            /// <summary>
            /// PlatformPaymentTypeEnum.AdyenCommission - AdyenCommission
            /// </summary>
            public static readonly PlatformPaymentTypeEnum AdyenCommission = new("AdyenCommission");

            /// <summary>
            /// PlatformPaymentTypeEnum.AdyenFees - AdyenFees
            /// </summary>
            public static readonly PlatformPaymentTypeEnum AdyenFees = new("AdyenFees");

            /// <summary>
            /// PlatformPaymentTypeEnum.AdyenMarkup - AdyenMarkup
            /// </summary>
            public static readonly PlatformPaymentTypeEnum AdyenMarkup = new("AdyenMarkup");

            /// <summary>
            /// PlatformPaymentTypeEnum.BalanceAccount - BalanceAccount
            /// </summary>
            public static readonly PlatformPaymentTypeEnum BalanceAccount = new("BalanceAccount");

            /// <summary>
            /// PlatformPaymentTypeEnum.ChargebackRemainder - ChargebackRemainder
            /// </summary>
            public static readonly PlatformPaymentTypeEnum ChargebackRemainder = new("ChargebackRemainder");

            /// <summary>
            /// PlatformPaymentTypeEnum.Commission - Commission
            /// </summary>
            public static readonly PlatformPaymentTypeEnum Commission = new("Commission");

            /// <summary>
            /// PlatformPaymentTypeEnum.DCCPlatformCommission - DCCPlatformCommission
            /// </summary>
            public static readonly PlatformPaymentTypeEnum DCCPlatformCommission = new("DCCPlatformCommission");

            /// <summary>
            /// PlatformPaymentTypeEnum.Default - Default
            /// </summary>
            public static readonly PlatformPaymentTypeEnum Default = new("Default");

            /// <summary>
            /// PlatformPaymentTypeEnum.Interchange - Interchange
            /// </summary>
            public static readonly PlatformPaymentTypeEnum Interchange = new("Interchange");

            /// <summary>
            /// PlatformPaymentTypeEnum.PaymentFee - PaymentFee
            /// </summary>
            public static readonly PlatformPaymentTypeEnum PaymentFee = new("PaymentFee");

            /// <summary>
            /// PlatformPaymentTypeEnum.Remainder - Remainder
            /// </summary>
            public static readonly PlatformPaymentTypeEnum Remainder = new("Remainder");

            /// <summary>
            /// PlatformPaymentTypeEnum.SchemeFee - SchemeFee
            /// </summary>
            public static readonly PlatformPaymentTypeEnum SchemeFee = new("SchemeFee");

            /// <summary>
            /// PlatformPaymentTypeEnum.Surcharge - Surcharge
            /// </summary>
            public static readonly PlatformPaymentTypeEnum Surcharge = new("Surcharge");

            /// <summary>
            /// PlatformPaymentTypeEnum.Tip - Tip
            /// </summary>
            public static readonly PlatformPaymentTypeEnum Tip = new("Tip");

            /// <summary>
            /// PlatformPaymentTypeEnum.TopUp - TopUp
            /// </summary>
            public static readonly PlatformPaymentTypeEnum TopUp = new("TopUp");

            /// <summary>
            /// PlatformPaymentTypeEnum.VAT - VAT
            /// </summary>
            public static readonly PlatformPaymentTypeEnum VAT = new("VAT");
        
            private PlatformPaymentTypeEnum(string? value)
            {
                Value = value;
            }

            /// <summary>
            /// Converts a string to a <see cref="PlatformPaymentTypeEnum"/> implicitly.
            /// </summary>
            /// <param name="value">The string value to convert. Defaults to null.</param>
            /// <returns>A new <see cref="PlatformPaymentTypeEnum"/> instance initialized with the string value.</returns>
            public static implicit operator PlatformPaymentTypeEnum?(string? value) => value == null ? null : new PlatformPaymentTypeEnum(value);
    
            /// <summary>
            /// Converts a <see cref="PlatformPaymentTypeEnum"/> instance to a string implicitly.
            /// </summary>
            /// <param name="option">The <see cref="PlatformPaymentTypeEnum"/> instance. Default to null.</param>
            /// <returns>String value of the <see cref="PlatformPaymentTypeEnum"/> instance./// </returns>
            public static implicit operator string?(PlatformPaymentTypeEnum? option) => option?.Value;
        
            public static bool operator ==(PlatformPaymentTypeEnum? left, PlatformPaymentTypeEnum? right) => string.Equals(left?.Value, right?.Value, StringComparison.OrdinalIgnoreCase);
    
            public static bool operator !=(PlatformPaymentTypeEnum? left, PlatformPaymentTypeEnum? right) => !string.Equals(left?.Value, right?.Value, StringComparison.OrdinalIgnoreCase);

            public override bool Equals(object? obj) => obj is PlatformPaymentTypeEnum other && string.Equals(Value, other.Value, StringComparison.OrdinalIgnoreCase);
    
            public override int GetHashCode() => Value?.GetHashCode() ?? 0;
        
            public override string ToString() => Value ?? string.Empty;
        
            /// <summary>
            /// Returns a <see cref="PlatformPaymentTypeEnum?"/>.
            /// </summary>
            /// <param name="value"></param>
            /// <returns><see cref="PlatformPaymentTypeEnum"/> or null.</returns>
            public static PlatformPaymentTypeEnum? FromStringOrDefault(string value)
            {
                return value switch {
                    "AcquiringFees" => PlatformPaymentTypeEnum.AcquiringFees,
                    "AdyenCommission" => PlatformPaymentTypeEnum.AdyenCommission,
                    "AdyenFees" => PlatformPaymentTypeEnum.AdyenFees,
                    "AdyenMarkup" => PlatformPaymentTypeEnum.AdyenMarkup,
                    "BalanceAccount" => PlatformPaymentTypeEnum.BalanceAccount,
                    "ChargebackRemainder" => PlatformPaymentTypeEnum.ChargebackRemainder,
                    "Commission" => PlatformPaymentTypeEnum.Commission,
                    "DCCPlatformCommission" => PlatformPaymentTypeEnum.DCCPlatformCommission,
                    "Default" => PlatformPaymentTypeEnum.Default,
                    "Interchange" => PlatformPaymentTypeEnum.Interchange,
                    "PaymentFee" => PlatformPaymentTypeEnum.PaymentFee,
                    "Remainder" => PlatformPaymentTypeEnum.Remainder,
                    "SchemeFee" => PlatformPaymentTypeEnum.SchemeFee,
                    "Surcharge" => PlatformPaymentTypeEnum.Surcharge,
                    "Tip" => PlatformPaymentTypeEnum.Tip,
                    "TopUp" => PlatformPaymentTypeEnum.TopUp,
                    "VAT" => PlatformPaymentTypeEnum.VAT,
                    _ => null,
                };
            }
    
            /// <summary>
            /// Converts the <see cref="PlatformPaymentTypeEnum"/> to the json value.
            /// </summary>
            /// <param name="value"><see cref="PlatformPaymentTypeEnum"/></param>
            /// <returns>String value of the enum.</returns>
            /// <exception cref="NotImplementedException"></exception>
            public static string? ToJsonValue(PlatformPaymentTypeEnum? value)
            {
                if (value == null)
                    return null;
            
                if (value == PlatformPaymentTypeEnum.AcquiringFees)
                    return "AcquiringFees";
                
                if (value == PlatformPaymentTypeEnum.AdyenCommission)
                    return "AdyenCommission";
                
                if (value == PlatformPaymentTypeEnum.AdyenFees)
                    return "AdyenFees";
                
                if (value == PlatformPaymentTypeEnum.AdyenMarkup)
                    return "AdyenMarkup";
                
                if (value == PlatformPaymentTypeEnum.BalanceAccount)
                    return "BalanceAccount";
                
                if (value == PlatformPaymentTypeEnum.ChargebackRemainder)
                    return "ChargebackRemainder";
                
                if (value == PlatformPaymentTypeEnum.Commission)
                    return "Commission";
                
                if (value == PlatformPaymentTypeEnum.DCCPlatformCommission)
                    return "DCCPlatformCommission";
                
                if (value == PlatformPaymentTypeEnum.Default)
                    return "Default";
                
                if (value == PlatformPaymentTypeEnum.Interchange)
                    return "Interchange";
                
                if (value == PlatformPaymentTypeEnum.PaymentFee)
                    return "PaymentFee";
                
                if (value == PlatformPaymentTypeEnum.Remainder)
                    return "Remainder";
                
                if (value == PlatformPaymentTypeEnum.SchemeFee)
                    return "SchemeFee";
                
                if (value == PlatformPaymentTypeEnum.Surcharge)
                    return "Surcharge";
                
                if (value == PlatformPaymentTypeEnum.Tip)
                    return "Tip";
                
                if (value == PlatformPaymentTypeEnum.TopUp)
                    return "TopUp";
                
                if (value == PlatformPaymentTypeEnum.VAT)
                    return "VAT";
                
                return null;
            }
            
            /// <summary>
            /// JsonConverter for writing PlatformPaymentTypeEnum.               
            /// </summary>
            public class PlatformPaymentTypeEnumJsonConverter : JsonConverter<PlatformPaymentTypeEnum>
            {
                public override PlatformPaymentTypeEnum? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions jsonOptions)
                {
                    string value = reader.GetString();
                    return value == null ? null : PlatformPaymentTypeEnum.FromStringOrDefault(value) ?? new PlatformPaymentTypeEnum(value);
                }

                public override void Write(Utf8JsonWriter writer, PlatformPaymentTypeEnum value, JsonSerializerOptions jsonOptions)
                {
                    writer.WriteStringValue(PlatformPaymentTypeEnum.ToJsonValue(value));
                }
            }
        }

        /// <summary>
        /// This is used to track if an optional field is set. If set, <see cref="PlatformPaymentType"/> will be populated.
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<PlatformPaymentTypeEnum?> _PlatformPaymentTypeOption { get; private set; }

        /// <summary>
        /// Specifies the nature of the transfer. This parameter helps categorize transfers so you can reconcile transactions at a later time, using the Balance Platform Accounting Report for [marketplaces](https://docs.adyen.com/marketplaces/reports-and-fees/balance-platform-accounting-report/) or [platforms](https://docs.adyen.com/platforms/reports-and-fees/balance-platform-accounting-report/).  Possible values:  * **AcquiringFees**: the acquiring fee (the aggregated amount of interchange and scheme fee) incurred on a transaction.  * **AdyenCommission**: the transaction fee due to Adyen under [blended rates](https://www.adyen.com/knowledge-hub/guides/payments-training-guide/get-the-best-from-your-card-processing).  * **AdyenFees**: all transaction fees due to Adyen. This is the aggregated amount of Adyen's commission and markup.  * **AdyenMarkup**: the transaction fee due to Adyen under [Interchange++ pricing](https://www.adyen.com/pricing).  * **BalanceAccount**: the amount booked to your user after the deduction of the relevant fees.  * **Commission**: your platform's or marketplace's commission on a transaction.  * **DCCPlatformCommission**: the Dynamic Currency Conversion (DCC) fee on a transaction.  * **Interchange**: the interchange fee (fee paid to the issuer) incurred on a transaction.  * **PaymentFee**: the aggregated amount of all transaction fees.  * **Remainder**: the leftover amount after currency conversion.  * **SchemeFee**: the scheme fee incurred on a transaction.  * **Surcharge**: the surcharge paid by the customer on a transaction.  * **Tip**: the tip paid by the customer.  * **TopUp**: an incoming transfer to top up your user's balance account.  * **VAT**: the value-added tax charged on the payment.
        /// </summary>
        /// <value>Specifies the nature of the transfer. This parameter helps categorize transfers so you can reconcile transactions at a later time, using the Balance Platform Accounting Report for [marketplaces](https://docs.adyen.com/marketplaces/reports-and-fees/balance-platform-accounting-report/) or [platforms](https://docs.adyen.com/platforms/reports-and-fees/balance-platform-accounting-report/).  Possible values:  * **AcquiringFees**: the acquiring fee (the aggregated amount of interchange and scheme fee) incurred on a transaction.  * **AdyenCommission**: the transaction fee due to Adyen under [blended rates](https://www.adyen.com/knowledge-hub/guides/payments-training-guide/get-the-best-from-your-card-processing).  * **AdyenFees**: all transaction fees due to Adyen. This is the aggregated amount of Adyen&#39;s commission and markup.  * **AdyenMarkup**: the transaction fee due to Adyen under [Interchange++ pricing](https://www.adyen.com/pricing).  * **BalanceAccount**: the amount booked to your user after the deduction of the relevant fees.  * **Commission**: your platform&#39;s or marketplace&#39;s commission on a transaction.  * **DCCPlatformCommission**: the Dynamic Currency Conversion (DCC) fee on a transaction.  * **Interchange**: the interchange fee (fee paid to the issuer) incurred on a transaction.  * **PaymentFee**: the aggregated amount of all transaction fees.  * **Remainder**: the leftover amount after currency conversion.  * **SchemeFee**: the scheme fee incurred on a transaction.  * **Surcharge**: the surcharge paid by the customer on a transaction.  * **Tip**: the tip paid by the customer.  * **TopUp**: an incoming transfer to top up your user&#39;s balance account.  * **VAT**: the value-added tax charged on the payment.</value>
        [JsonPropertyName("platformPaymentType")]
        public PlatformPaymentTypeEnum? PlatformPaymentType { get { return this._PlatformPaymentTypeOption; } set { this._PlatformPaymentTypeOption = new(value); } }

        /// <summary>
        /// **platformPayment**
        /// </summary>
        /// <value>**platformPayment**</value>
        [JsonConverter(typeof(TypeEnumJsonConverter))]
        public class TypeEnum : IEnum
        {
            /// <summary>
            /// Returns the value of the TypeEnum.
            /// </summary>
            public string? Value { get; set; }

            /// <summary>
            /// TypeEnum.PlatformPayment - platformPayment
            /// </summary>
            public static readonly TypeEnum PlatformPayment = new("platformPayment");
        
            private TypeEnum(string? value)
            {
                Value = value;
            }

            /// <summary>
            /// Converts a string to a <see cref="TypeEnum"/> implicitly.
            /// </summary>
            /// <param name="value">The string value to convert. Defaults to null.</param>
            /// <returns>A new <see cref="TypeEnum"/> instance initialized with the string value.</returns>
            public static implicit operator TypeEnum?(string? value) => value == null ? null : new TypeEnum(value);
    
            /// <summary>
            /// Converts a <see cref="TypeEnum"/> instance to a string implicitly.
            /// </summary>
            /// <param name="option">The <see cref="TypeEnum"/> instance. Default to null.</param>
            /// <returns>String value of the <see cref="TypeEnum"/> instance./// </returns>
            public static implicit operator string?(TypeEnum? option) => option?.Value;
        
            public static bool operator ==(TypeEnum? left, TypeEnum? right) => string.Equals(left?.Value, right?.Value, StringComparison.OrdinalIgnoreCase);
    
            public static bool operator !=(TypeEnum? left, TypeEnum? right) => !string.Equals(left?.Value, right?.Value, StringComparison.OrdinalIgnoreCase);

            public override bool Equals(object? obj) => obj is TypeEnum other && string.Equals(Value, other.Value, StringComparison.OrdinalIgnoreCase);
    
            public override int GetHashCode() => Value?.GetHashCode() ?? 0;
        
            public override string ToString() => Value ?? string.Empty;
        
            /// <summary>
            /// Returns a <see cref="TypeEnum?"/>.
            /// </summary>
            /// <param name="value"></param>
            /// <returns><see cref="TypeEnum"/> or null.</returns>
            public static TypeEnum? FromStringOrDefault(string value)
            {
                return value switch {
                    "platformPayment" => TypeEnum.PlatformPayment,
                    _ => null,
                };
            }
    
            /// <summary>
            /// Converts the <see cref="TypeEnum"/> to the json value.
            /// </summary>
            /// <param name="value"><see cref="TypeEnum"/></param>
            /// <returns>String value of the enum.</returns>
            /// <exception cref="NotImplementedException"></exception>
            public static string? ToJsonValue(TypeEnum? value)
            {
                if (value == null)
                    return null;
            
                if (value == TypeEnum.PlatformPayment)
                    return "platformPayment";
                
                return null;
            }
            
            /// <summary>
            /// JsonConverter for writing TypeEnum.               
            /// </summary>
            public class TypeEnumJsonConverter : JsonConverter<TypeEnum>
            {
                public override TypeEnum? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions jsonOptions)
                {
                    string value = reader.GetString();
                    return value == null ? null : TypeEnum.FromStringOrDefault(value) ?? new TypeEnum(value);
                }

                public override void Write(Utf8JsonWriter writer, TypeEnum value, JsonSerializerOptions jsonOptions)
                {
                    writer.WriteStringValue(TypeEnum.ToJsonValue(value));
                }
            }
        }

        /// <summary>
        /// This is used to track if an optional field is set. If set, <see cref="Type"/> will be populated.
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<TypeEnum?> _TypeOption { get; private set; }

        /// <summary>
        /// **platformPayment**
        /// </summary>
        /// <value>**platformPayment**</value>
        [JsonPropertyName("type")]
        public TypeEnum? Type { get { return this._TypeOption; } set { this._TypeOption = new(value); } }

        /// <summary>
        /// This is used to track if an optional field is set. If set, <see cref="ModificationMerchantReference"/> will be populated.
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> _ModificationMerchantReferenceOption { get; private set; }

        /// <summary>
        /// The capture&#39;s merchant reference included in the transfer.
        /// </summary>
        /// <value>The capture's merchant reference included in the transfer.</value>
        [JsonPropertyName("modificationMerchantReference")]
        public string? ModificationMerchantReference { get { return this._ModificationMerchantReferenceOption; } set { this._ModificationMerchantReferenceOption = new(value); } }

        /// <summary>
        /// This is used to track if an optional field is set. If set, <see cref="ModificationPspReference"/> will be populated.
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> _ModificationPspReferenceOption { get; private set; }

        /// <summary>
        /// The capture reference included in the transfer.
        /// </summary>
        /// <value>The capture reference included in the transfer.</value>
        [JsonPropertyName("modificationPspReference")]
        public string? ModificationPspReference { get { return this._ModificationPspReferenceOption; } set { this._ModificationPspReferenceOption = new(value); } }

        /// <summary>
        /// This is used to track if an optional field is set. If set, <see cref="PaymentMerchantReference"/> will be populated.
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> _PaymentMerchantReferenceOption { get; private set; }

        /// <summary>
        /// The payment&#39;s merchant reference included in the transfer.
        /// </summary>
        /// <value>The payment's merchant reference included in the transfer.</value>
        [JsonPropertyName("paymentMerchantReference")]
        public string? PaymentMerchantReference { get { return this._PaymentMerchantReferenceOption; } set { this._PaymentMerchantReferenceOption = new(value); } }

        /// <summary>
        /// This is used to track if an optional field is set. If set, <see cref="PspPaymentReference"/> will be populated.
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> _PspPaymentReferenceOption { get; private set; }

        /// <summary>
        /// The payment reference included in the transfer.
        /// </summary>
        /// <value>The payment reference included in the transfer.</value>
        [JsonPropertyName("pspPaymentReference")]
        public string? PspPaymentReference { get { return this._PspPaymentReferenceOption; } set { this._PspPaymentReferenceOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PlatformPayment {\n");
            sb.Append("  ModificationMerchantReference: ").Append(ModificationMerchantReference).Append("\n");
            sb.Append("  ModificationPspReference: ").Append(ModificationPspReference).Append("\n");
            sb.Append("  PaymentMerchantReference: ").Append(PaymentMerchantReference).Append("\n");
            sb.Append("  PlatformPaymentType: ").Append(PlatformPaymentType).Append("\n");
            sb.Append("  PspPaymentReference: ").Append(PspPaymentReference).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PlatformPayment" />
    /// </summary>
    public class PlatformPaymentJsonConverter : JsonConverter<PlatformPayment>
    {
        /// <summary>
        /// Deserializes json to <see cref="PlatformPayment"/>.
        /// </summary>
        /// <param name="utf8JsonReader"><see cref="Utf8JsonReader"/>.</param>
        /// <param name="typeToConvert"><see cref="Type"/>.</param>
        /// <param name="jsonSerializerOptions">The <see cref="JsonSerializerOptions"/>, initialized from <see cref="HostConfiguration"/>.</param>
        /// <returns><see cref="PlatformPayment"/>.</returns>
        /// <exception cref="JsonException"></exception>
        public override PlatformPayment Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> modificationMerchantReference = default;
            Option<string?> modificationPspReference = default;
            Option<string?> paymentMerchantReference = default;
            Option<PlatformPayment.PlatformPaymentTypeEnum?> platformPaymentType = default;
            Option<string?> pspPaymentReference = default;
            Option<PlatformPayment.TypeEnum?> type = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? jsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (jsonPropertyName)
                    {
                        case "modificationMerchantReference":
                            modificationMerchantReference = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "modificationPspReference":
                            modificationPspReference = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "paymentMerchantReference":
                            paymentMerchantReference = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "platformPaymentType":
                            string? platformPaymentTypeRawValue = utf8JsonReader.GetString();
                            platformPaymentType = new Option<PlatformPayment.PlatformPaymentTypeEnum?>(PlatformPayment.PlatformPaymentTypeEnum.FromStringOrDefault(platformPaymentTypeRawValue));
                            break;
                        case "pspPaymentReference":
                            pspPaymentReference = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            type = new Option<PlatformPayment.TypeEnum?>(PlatformPayment.TypeEnum.FromStringOrDefault(typeRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }
            

            return new PlatformPayment(modificationMerchantReference, modificationPspReference, paymentMerchantReference, platformPaymentType, pspPaymentReference, type);
        }

        /// <summary>
        /// Serializes a <see cref="PlatformPayment"/>.
        /// </summary>
        /// <param name="writer"><see cref="Utf8JsonWriter"/></param>
        /// <param name="platformPayment"></param>
        /// <param name="jsonSerializerOptions"><see cref="JsonSerializerOptions"/></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PlatformPayment platformPayment, JsonSerializerOptions jsonSerializerOptions)
        {
            
            writer.WriteStartObject();
            
            WriteProperties(writer, platformPayment, jsonSerializerOptions);
            
            writer.WriteEndObject();
            
        }

        /// <summary>
        /// Serializes the properties of <see cref="PlatformPayment"/>.
        /// </summary>
        /// <param name="writer"><see creft="Utf8JsonWriter"/></param>
        /// <param name="platformPayment"></param>
        /// <param name="jsonSerializerOptions"><see cref="JsonSerializerOptions"/></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PlatformPayment platformPayment, JsonSerializerOptions jsonSerializerOptions)
        {
            
            if (platformPayment._ModificationMerchantReferenceOption.IsSet)
                if (platformPayment.ModificationMerchantReference != null)
                    writer.WriteString("modificationMerchantReference", platformPayment.ModificationMerchantReference);

            if (platformPayment._ModificationPspReferenceOption.IsSet)
                if (platformPayment.ModificationPspReference != null)
                    writer.WriteString("modificationPspReference", platformPayment.ModificationPspReference);

            if (platformPayment._PaymentMerchantReferenceOption.IsSet)
                if (platformPayment.PaymentMerchantReference != null)
                    writer.WriteString("paymentMerchantReference", platformPayment.PaymentMerchantReference);

            if (platformPayment._PlatformPaymentTypeOption.IsSet && platformPayment.PlatformPaymentType != null) 
            {
                string? platformPaymentTypeRawValue = PlatformPayment.PlatformPaymentTypeEnum.ToJsonValue(platformPayment._PlatformPaymentTypeOption.Value!.Value);
                writer.WriteString("platformPaymentType", platformPaymentTypeRawValue);
            }
            
            if (platformPayment._PspPaymentReferenceOption.IsSet)
                if (platformPayment.PspPaymentReference != null)
                    writer.WriteString("pspPaymentReference", platformPayment.PspPaymentReference);

            if (platformPayment._TypeOption.IsSet && platformPayment.Type != null) 
            {
                string? typeRawValue = PlatformPayment.TypeEnum.ToJsonValue(platformPayment._TypeOption.Value!.Value);
                writer.WriteString("type", typeRawValue);
            }
        }
    }
}
