// <auto-generated>
/*
 * Disputes API
 *
 * You can use the [Disputes API](https://docs.adyen.com/risk-management/disputes-api) to automate the dispute handling process so that you can respond to disputes and chargebacks as soon as they are initiated. The Disputes API lets you retrieve defense reasons, supply and delete defense documents, and accept or defend disputes.  ## Authentication Each request to the Disputes API must be signed with an API key. For this, obtain an API Key from your Customer Area, as described in [How to get the API key](https://docs.adyen.com/development-resources/api-credentials#generate-api-key). Then set this key to the `X-API-Key` header value, for example:  ``` curl -H \"Content-Type: application/json\" \\ -H \"X-API-Key: Your_API_key\" \\ ... ``` Note that when going live, you need to generate new web service user credentials to access the [live endpoints](https://docs.adyen.com/development-resources/live-endpoints).  ## Versioning Disputes API supports [versioning](https://docs.adyen.com/development-resources/versioning) using a version suffix in the endpoint URL. This suffix has the following format: \"vXX\", where XX is the version number.  For example: ``` https://ca-test.adyen.com/ca/services/DisputeService/v30/defendDispute ```
 *
 * The version of the OpenAPI document: 30
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Adyen.Core;
using Adyen.Disputes.Client;

namespace Adyen.Disputes.Models
{
    /// <summary>
    /// DisputeServiceResult.
    /// </summary>
    public partial class DisputeServiceResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DisputeServiceResult" /> class.
        /// </summary>
        /// <param name="success">Indicates whether the request succeeded.</param>
        /// <param name="errorMessage">The general error message.</param>
        [JsonConstructor]
        public DisputeServiceResult(bool success, Option<string?> errorMessage = default)
        {
            Success = success;
            _ErrorMessageOption = errorMessage;
            OnCreated();
        }
        
        /// <summary>
        /// Best practice: Use the constructor to initialize your objects to understand which parameters are required/optional.
        /// </summary>
        public DisputeServiceResult()
        {
        }

        partial void OnCreated();

        /// <summary>
        /// Indicates whether the request succeeded.
        /// </summary>
        /// <value>Indicates whether the request succeeded.</value>
        [JsonPropertyName("success")]
        public bool Success { get; set; }

        /// <summary>
        /// This is used to track if an optional field is set. If set, <see cref="ErrorMessage"/> will be populated.
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> _ErrorMessageOption { get; private set; }

        /// <summary>
        /// The general error message.
        /// </summary>
        /// <value>The general error message.</value>
        [JsonPropertyName("errorMessage")]
        public string? ErrorMessage { get { return this._ErrorMessageOption; } set { this._ErrorMessageOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DisputeServiceResult {\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  ErrorMessage: ").Append(ErrorMessage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DisputeServiceResult" />
    /// </summary>
    public class DisputeServiceResultJsonConverter : JsonConverter<DisputeServiceResult>
    {
        /// <summary>
        /// Deserializes json to <see cref="DisputeServiceResult"/>.
        /// </summary>
        /// <param name="utf8JsonReader"><see cref="Utf8JsonReader"/>.</param>
        /// <param name="typeToConvert"><see cref="Type"/>.</param>
        /// <param name="jsonSerializerOptions">The <see cref="JsonSerializerOptions"/>, initialized from <see cref="HostConfiguration"/>.</param>
        /// <returns><see cref="DisputeServiceResult"/>.</returns>
        /// <exception cref="JsonException"></exception>
        public override DisputeServiceResult Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> success = default;
            Option<string?> errorMessage = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? jsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (jsonPropertyName)
                    {
                        case "success":
                            success = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "errorMessage":
                            errorMessage = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }
            
            if (!success.IsSet)
                throw new ArgumentException("Property is required for class DisputeServiceResult.", nameof(success));

            return new DisputeServiceResult(success.Value!.Value!, errorMessage);
        }

        /// <summary>
        /// Serializes a <see cref="DisputeServiceResult"/>.
        /// </summary>
        /// <param name="writer"><see cref="Utf8JsonWriter"/></param>
        /// <param name="disputeServiceResult"></param>
        /// <param name="jsonSerializerOptions"><see cref="JsonSerializerOptions"/></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DisputeServiceResult disputeServiceResult, JsonSerializerOptions jsonSerializerOptions)
        {
            
            writer.WriteStartObject();
            
            WriteProperties(writer, disputeServiceResult, jsonSerializerOptions);
            
            writer.WriteEndObject();
            
        }

        /// <summary>
        /// Serializes the properties of <see cref="DisputeServiceResult"/>.
        /// </summary>
        /// <param name="writer"><see creft="Utf8JsonWriter"/></param>
        /// <param name="disputeServiceResult"></param>
        /// <param name="jsonSerializerOptions"><see cref="JsonSerializerOptions"/></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DisputeServiceResult disputeServiceResult, JsonSerializerOptions jsonSerializerOptions)
        {
            
            writer.WriteBoolean("success", disputeServiceResult.Success);

            if (disputeServiceResult._ErrorMessageOption.IsSet)
                if (disputeServiceResult.ErrorMessage != null)
                    writer.WriteString("errorMessage", disputeServiceResult.ErrorMessage);
        }
    }
}
