/*
 * Configuration API
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/

#nullable enable

using System;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Adyen.BalancePlatform;
using Adyen.BalancePlatform.Client;

namespace Adyen.BalancePlatform.Extensions
{
    /// <summary>
    /// Extension methods for <see cref="IHostBuilder"/>.
    /// </summary>
    public static class HostBuilderExtensions
    {
        /// <summary>
        /// Initializes the <see cref="HostConfiguration"/> *without* adding the BalancePlatform API services defaults to the <see cref="IServiceCollection"/>.
        /// Use <see cref="Adyen.BalancePlatform.Extensions.IServiceCollectionExtensions"/> to add the BalancePlatform API services to the <see cref="IServiceCollection"/>.
        /// </summary>
        /// <param name="hostBuilder"><see cref="IHostBuilder"/>.</param>
        /// <param name="hostConfigurationOptions">Configures the <see cref="HostBuilderContext"/>, <see cref="IServiceCollection"/>, and <see cref="HostConfiguration"/>.</param>
        public static IHostBuilder ConfigureBalancePlatform(this IHostBuilder hostBuilder, Action<HostBuilderContext, IServiceCollection, HostConfiguration> hostConfigurationOptions)
        {
            hostBuilder.ConfigureServices((context, services) => 
            {
                HostConfiguration hostConfiguration = new HostConfiguration(services);
    
                hostConfigurationOptions(context, services, hostConfiguration);
            });

            return hostBuilder;
        }
    
        /// <summary>
        /// Initializes the <see cref="HostConfiguration"/> *and* adds the BalancePlatform API services defaults to the <see cref="IServiceCollection"/>.
        /// You can (optionally) configure the <see cref="ServiceLifetime"/>, the <see cref="System.Net.Http.HttpClient"/> (timeouts) and <see cref="IHttpClientBuilder"/>.
        /// </summary>
        /// <param name="hostBuilder"><see cref="IHostBuilder"/>.</param>
        /// <param name="hostConfigurationOptions">Configures the <see cref="HostBuilderContext"/>, <see cref="IServiceCollection"/>, and <see cref="HostConfiguration"/>.</param>
        /// <param name="serviceLifetime"><see cref="ServiceLifetime"/>.</param>
        /// <param name="httpClientOptions">Configures the <see cref="System.Net.Http.HttpClient"/>.</param>
        /// <param name="httpClientBuilderOptions">Configures the <see cref="IHttpClientBuilder"/>.</param>
        public static IHostBuilder ConfigureBalancePlatformDefaults(this IHostBuilder hostBuilder, Action<HostBuilderContext, IServiceCollection, HostConfiguration> hostConfigurationOptions, ServiceLifetime serviceLifetime = ServiceLifetime.Singleton, Action<System.Net.Http.HttpClient>? httpClientOptions = null, Action<IHttpClientBuilder>? httpClientBuilderOptions = null)
        {
            hostBuilder.ConfigureServices((context, services) => 
            {
                HostConfiguration hostConfiguration = new HostConfiguration(services);
        
                hostConfigurationOptions(context, services, hostConfiguration);
                services.AddAllBalancePlatformServices(serviceLifetime, httpClientOptions, httpClientBuilderOptions);
                
                
            });

            return hostBuilder;
        }
    }
}
