// <auto-generated>
/*
 * Configuration webhooks
 *
 * Adyen sends webhooks to inform your system about events that occur in your platform. These events include, for example, when an account holder's capabilities are updated, or when a sweep configuration is created or updated.  When an event occurs, Adyen makes an HTTP POST request to a URL on your server and includes the details of the event in the request body.  You can use these webhooks to build your implementation. For example, you can use this information to update internal statuses when the status of a capability is changed.
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Adyen.Core;
using Adyen.ConfigurationWebhooks.Client;

namespace Adyen.ConfigurationWebhooks.Models
{
    /// <summary>
    /// ValidationFacts.
    /// </summary>
    public partial class ValidationFacts : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ValidationFacts" /> class.
        /// </summary>
        /// <param name="reasons">The reason for the &#x60;result&#x60; of the validations.  This field is only sent for &#x60;validationFacts.type&#x60; **walletValidation**, when &#x60;validationFacts.result&#x60; is **invalid**.</param>
        /// <param name="result">The evaluation result of the validation facts.  Possible values: **valid**, **invalid**, **notValidated**, **notApplicable**.</param>
        /// <param name="type">The type of the validation fact.</param>
        [JsonConstructor]
        public ValidationFacts(Option<List<string>?> reasons = default, Option<ResultEnum?> result = default, Option<string?> type = default)
        {
            _ReasonsOption = reasons;
            _ResultOption = result;
            _TypeOption = type;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The evaluation result of the validation facts.  Possible values: **valid**, **invalid**, **notValidated**, **notApplicable**.
        /// </summary>
        /// <value>The evaluation result of the validation facts.  Possible values: **valid**, **invalid**, **notValidated**, **notApplicable**.</value>
        [JsonConverter(typeof(ResultEnumJsonConverter))]
        public class ResultEnum : IEnum
        {
            /// <summary>
            /// Returns the value of the ResultEnum.
            /// </summary>
            public string? Value { get; set; }

            /// <summary>
            /// ResultEnum.Invalid - invalid
            /// </summary>
            public static readonly ResultEnum Invalid = new("invalid");

            /// <summary>
            /// ResultEnum.NotApplicable - notApplicable
            /// </summary>
            public static readonly ResultEnum NotApplicable = new("notApplicable");

            /// <summary>
            /// ResultEnum.NotValidated - notValidated
            /// </summary>
            public static readonly ResultEnum NotValidated = new("notValidated");

            /// <summary>
            /// ResultEnum.Valid - valid
            /// </summary>
            public static readonly ResultEnum Valid = new("valid");
        
            private ResultEnum(string? value)
            {
                Value = value;
            }

            /// <summary>
            /// Converts a string to a <see cref="ResultEnum"/> implicitly.
            /// </summary>
            /// <param name="value">The string value to convert. Defaults to null.</param>
            /// <returns>A new <see cref="ResultEnum"/> instance initialized with the string value.</returns>
            public static implicit operator ResultEnum?(string? value) => value == null ? null : new ResultEnum(value);
    
            /// <summary>
            /// Converts a <see cref="ResultEnum"/> instance to a string implicitly.
            /// </summary>
            /// <param name="option">The <see cref="ResultEnum"/> instance. Default to null.</param>
            /// <returns>String value of the <see cref="ResultEnum"/> instance./// </returns>
            public static implicit operator string?(ResultEnum? option) => option?.Value;
        
            public static bool operator ==(ResultEnum? left, ResultEnum? right) => string.Equals(left?.Value, right?.Value, StringComparison.OrdinalIgnoreCase);
    
            public static bool operator !=(ResultEnum? left, ResultEnum? right) => !string.Equals(left?.Value, right?.Value, StringComparison.OrdinalIgnoreCase);

            public override bool Equals(object? obj) => obj is ResultEnum other && string.Equals(Value, other.Value, StringComparison.OrdinalIgnoreCase);
    
            public override int GetHashCode() => Value?.GetHashCode() ?? 0;
        
            public override string ToString() => Value ?? string.Empty;
        
            /// <summary>
            /// Returns a <see cref="ResultEnum?"/>.
            /// </summary>
            /// <param name="value"></param>
            /// <returns><see cref="ResultEnum"/> or null.</returns>
            public static ResultEnum? FromStringOrDefault(string value)
            {
                return value switch {
                    "invalid" => ResultEnum.Invalid,
                    "notApplicable" => ResultEnum.NotApplicable,
                    "notValidated" => ResultEnum.NotValidated,
                    "valid" => ResultEnum.Valid,
                    _ => null,
                };
            }
    
            /// <summary>
            /// Converts the <see cref="ResultEnum"/> to the json value.
            /// </summary>
            /// <param name="value"><see cref="ResultEnum"/></param>
            /// <returns>String value of the enum.</returns>
            /// <exception cref="NotImplementedException"></exception>
            public static string? ToJsonValue(ResultEnum? value)
            {
                if (value == null)
                    return null;
            
                if (value == ResultEnum.Invalid)
                    return "invalid";
                
                if (value == ResultEnum.NotApplicable)
                    return "notApplicable";
                
                if (value == ResultEnum.NotValidated)
                    return "notValidated";
                
                if (value == ResultEnum.Valid)
                    return "valid";
                
                return null;
            }
            
            /// <summary>
            /// JsonConverter for writing ResultEnum.               
            /// </summary>
            public class ResultEnumJsonConverter : JsonConverter<ResultEnum>
            {
                public override ResultEnum? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions jsonOptions)
                {
                    string value = reader.GetString();
                    return value == null ? null : ResultEnum.FromStringOrDefault(value) ?? new ResultEnum(value);
                }

                public override void Write(Utf8JsonWriter writer, ResultEnum value, JsonSerializerOptions jsonOptions)
                {
                    writer.WriteStringValue(ResultEnum.ToJsonValue(value));
                }
            }
        }

         /// <summary>
        /// Used to track if an optional field is set. If set, <see cref="Result"/> will be populated.
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ResultEnum?> _ResultOption { get; private set; }

        /// <summary>
        /// The evaluation result of the validation facts.  Possible values: **valid**, **invalid**, **notValidated**, **notApplicable**.
        /// </summary>
        /// <value>The evaluation result of the validation facts.  Possible values: **valid**, **invalid**, **notValidated**, **notApplicable**.</value>
        [JsonPropertyName("result")]
        public ResultEnum? Result { get { return this._ResultOption; } set { this._ResultOption = new(value); } }

        /// <summary>
        /// Used to track the state of Reasons
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> _ReasonsOption { get; private set; }

        /// <summary>
        /// The reason for the &#x60;result&#x60; of the validations.  This field is only sent for &#x60;validationFacts.type&#x60; **walletValidation**, when &#x60;validationFacts.result&#x60; is **invalid**.
        /// </summary>
        /// <value>The reason for the &#x60;result&#x60; of the validations.  This field is only sent for &#x60;validationFacts.type&#x60; **walletValidation**, when &#x60;validationFacts.result&#x60; is **invalid**.</value>
        [JsonPropertyName("reasons")]
        public List<string>? Reasons { get { return this._ReasonsOption; } set { this._ReasonsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Type
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> _TypeOption { get; private set; }

        /// <summary>
        /// The type of the validation fact.
        /// </summary>
        /// <value>The type of the validation fact.</value>
        [JsonPropertyName("type")]
        public string? Type { get { return this._TypeOption; } set { this._TypeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ValidationFacts {\n");
            sb.Append("  Reasons: ").Append(Reasons).Append("\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ValidationFacts" />
    /// </summary>
    public class ValidationFactsJsonConverter : JsonConverter<ValidationFacts>
    {
        /// <summary>
        /// Deserializes json to <see cref="ValidationFacts"/>.
        /// </summary>
        /// <param name="utf8JsonReader"><see cref="Utf8JsonReader"/>.</param>
        /// <param name="typeToConvert"><see cref="Type"/>.</param>
        /// <param name="jsonSerializerOptions">The <see cref="JsonSerializerOptions"/>, initialized from <see cref="HostConfiguration"/>.</param>
        /// <returns><see cref="ValidationFacts"/>.</returns>
        /// <exception cref="JsonException"></exception>
        public override ValidationFacts Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<string>?> reasons = default;
            Option<ValidationFacts.ResultEnum?> result = default;
            Option<string?> type = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? jsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (jsonPropertyName)
                    {
                        case "reasons":
                            reasons = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "result":
                            string? resultRawValue = utf8JsonReader.GetString();
                            result = new Option<ValidationFacts.ResultEnum?>(ValidationFacts.ResultEnum.FromStringOrDefault(resultRawValue));
                            break;
                        case "type":
                            type = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }
            

            return new ValidationFacts(reasons, result, type);
        }

        /// <summary>
        /// Serializes a <see cref="ValidationFacts"/>.
        /// </summary>
        /// <param name="writer"><see cref="Utf8JsonWriter"/></param>
        /// <param name="validationFacts"></param>
        /// <param name="jsonSerializerOptions"><see cref="JsonSerializerOptions"/></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ValidationFacts validationFacts, JsonSerializerOptions jsonSerializerOptions)
        {
            
            writer.WriteStartObject();
            
            WriteProperties(writer, validationFacts, jsonSerializerOptions);
            
            writer.WriteEndObject();
            
        }

        /// <summary>
        /// Serializes the properties of <see cref="ValidationFacts"/>.
        /// </summary>
        /// <param name="writer"><see creft="Utf8JsonWriter"/></param>
        /// <param name="validationFacts"></param>
        /// <param name="jsonSerializerOptions"><see cref="JsonSerializerOptions"/></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ValidationFacts validationFacts, JsonSerializerOptions jsonSerializerOptions)
        {
            
            if (validationFacts._ReasonsOption.IsSet)
            {
                writer.WritePropertyName("reasons");
                JsonSerializer.Serialize(writer, validationFacts.Reasons, jsonSerializerOptions);
            }
            if (validationFacts._ResultOption.IsSet && validationFacts.Result != null) 
            {
                string? resultRawValue = ValidationFacts.ResultEnum.ToJsonValue(validationFacts._ResultOption.Value!.Value);
                writer.WriteString("result", resultRawValue);
            }
            
            if (validationFacts._TypeOption.IsSet)
                if (validationFacts.Type != null)
                    writer.WriteString("type", validationFacts.Type);
        }
    }
}
