// <auto-generated>
/*
 * Capital API
 *
 * The Capital API provides endpoints for embedding Adyen Capital into your [marketplace](https://docs.adyen.com/platforms/capital) or [platform](https://docs.adyen.com/platforms/capital). With Capital, you can offer business financing to your users as grants. When a user receives a grant, they must repay the grant amount in a specified term, in addition to paying a fee for using this service.  With these endpoints, you can: - **Get available grant offers**: You can get the grant offers that are available for your users. Adyen configures the financing amount, the fee, and the repayment conditions for each offer. These configurations are based on proactive risk analyses that Adyen performs on your users. - **Make requests for grants**: When a user selects a grant offer, you can make a request for the grant on their behalf. - **Get information about your grant account**: Your grant account tracks the information of all grants in your marketplace or platform.  ## Authentication Each request made to the Capital API must be signed with an API key. Generate an API key in your Customer Area.  To connect to the API, add an `X-API-Key` header with the API key as the value, for example:   ``` curl -H \"Content-Type: application/json\" \\ -H \"X-API-Key: YOUR_API_KEY\" \\ ... ```  ## Roles and permissions To use the Capital API, your API credential must have the following roles: - **Balance_Platform_Capital_Configuration_Role** - **Balance_Platform_Capital_Grant_Initiation_Role**  Reach out to your Adyen contact to set up these roles. ## Going live When going live, generate an API key in your [live Customer Area](https://ca-live.adyen.com/ca). You can then use the API key to send requests to `https://balanceplatform-api-live.adyen.com/capital/v{version}`.  
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Adyen.Core;
using Adyen.Capital.Client;

namespace Adyen.Capital.Models
{
    /// <summary>
    /// Action.
    /// </summary>
    public partial class Action
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Action" /> class.
        /// </summary>
        /// <param name="actionCode">The code identifying the action that needs to be completed.</param>
        /// <param name="resolved">Indicates whether this action has been successfully completed.</param>
        [JsonConstructor]
        public Action(string actionCode, bool resolved)
        {
            ActionCode = actionCode;
            Resolved = resolved;
            OnCreated();
        }
        
        /// <summary>
        /// Best practice: Use the constructor to initialize your objects to understand which parameters are required/optional.
        /// </summary>
        public Action()
        {
        }

        partial void OnCreated();

        /// <summary>
        /// The code identifying the action that needs to be completed.
        /// </summary>
        /// <value>The code identifying the action that needs to be completed.</value>
        [JsonPropertyName("actionCode")]
        public string ActionCode { get; set; }

        /// <summary>
        /// Indicates whether this action has been successfully completed.
        /// </summary>
        /// <value>Indicates whether this action has been successfully completed.</value>
        [JsonPropertyName("resolved")]
        public bool Resolved { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Action {\n");
            sb.Append("  ActionCode: ").Append(ActionCode).Append("\n");
            sb.Append("  Resolved: ").Append(Resolved).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Action" />
    /// </summary>
    public class ActionJsonConverter : JsonConverter<Action>
    {
        /// <summary>
        /// Deserializes json to <see cref="Action"/>.
        /// </summary>
        /// <param name="utf8JsonReader"><see cref="Utf8JsonReader"/>.</param>
        /// <param name="typeToConvert"><see cref="Type"/>.</param>
        /// <param name="jsonSerializerOptions">The <see cref="JsonSerializerOptions"/>, initialized from <see cref="HostConfiguration"/>.</param>
        /// <returns><see cref="Action"/>.</returns>
        /// <exception cref="JsonException"></exception>
        public override Action Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> actionCode = default;
            Option<bool?> resolved = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? jsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (jsonPropertyName)
                    {
                        case "actionCode":
                            actionCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "resolved":
                            resolved = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }
            

            return new Action(actionCode.Value!, resolved.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="Action"/>.
        /// </summary>
        /// <param name="writer"><see cref="Utf8JsonWriter"/></param>
        /// <param name="action"></param>
        /// <param name="jsonSerializerOptions"><see cref="JsonSerializerOptions"/></param>
        public override void Write(Utf8JsonWriter writer, Action action, JsonSerializerOptions jsonSerializerOptions)
        {
            
            writer.WriteStartObject();
            
            WriteProperties(writer, action, jsonSerializerOptions);
            
            writer.WriteEndObject();
            
        }

        /// <summary>
        /// Serializes the properties of <see cref="Action"/>.
        /// </summary>
        /// <param name="writer"><see cref="Utf8JsonWriter"/></param>
        /// <param name="action"></param>
        /// <param name="jsonSerializerOptions"><see cref="JsonSerializerOptions"/></param>
        public void WriteProperties(Utf8JsonWriter writer, Action action, JsonSerializerOptions jsonSerializerOptions)
        {
            
            if (action.ActionCode != null)
                writer.WriteString("actionCode", action.ActionCode);

            writer.WriteBoolean("resolved", action.Resolved);
        }
    }
}
