// <auto-generated>
/*
 * Management API
 *
 * Configure and manage your Adyen company and merchant accounts, stores, and payment terminals. ## Authentication Each request to the Management API must be signed with an API key. [Generate your API key](https://docs.adyen.com/development-resources/api-credentials#generate-api-key) in the Customer Area and then set this key to the `X-API-Key` header value.  To access the live endpoints, you need to generate a new API key in your live Customer Area. ## Versioning  Management API handles versioning as part of the endpoint URL. For example, to send a request to this version of the `/companies/{companyId}/webhooks` endpoint, use:  ```text https://management-test.adyen.com/v3/companies/{companyId}/webhooks ```  ## Going live  To access the live endpoints, you need an API key from your live Customer Area. Use this API key to make requests to:  ```text https://management-live.adyen.com/v3 ```  ## Release notes Have a look at the [release notes](https://docs.adyen.com/release-notes/management-api) to find out what changed in this version!
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Adyen.Core;
using Adyen.Management.Client;

namespace Adyen.Management.Models
{
    /// <summary>
    /// CompanyLinks.
    /// </summary>
    public partial class CompanyLinks : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CompanyLinks" /> class.
        /// </summary>
        /// <param name="self">self</param>
        /// <param name="apiCredentials">apiCredentials</param>
        /// <param name="users">users</param>
        /// <param name="webhooks">webhooks</param>
        [JsonConstructor]
        public CompanyLinks(LinksElement self, Option<LinksElement?> apiCredentials = default, Option<LinksElement?> users = default, Option<LinksElement?> webhooks = default)
        {
            Self = self;
            _ApiCredentialsOption = apiCredentials;
            _UsersOption = users;
            _WebhooksOption = webhooks;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Self
        /// </summary>
        [JsonPropertyName("self")]
        public LinksElement Self { get; set; }

        /// <summary>
        /// Used to track the state of ApiCredentials
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<LinksElement?> _ApiCredentialsOption { get; private set; }

        /// <summary>
        /// Gets or Sets ApiCredentials
        /// </summary>
        [JsonPropertyName("apiCredentials")]
        public LinksElement? ApiCredentials { get { return this._ApiCredentialsOption; } set { this._ApiCredentialsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Users
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<LinksElement?> _UsersOption { get; private set; }

        /// <summary>
        /// Gets or Sets Users
        /// </summary>
        [JsonPropertyName("users")]
        public LinksElement? Users { get { return this._UsersOption; } set { this._UsersOption = new(value); } }

        /// <summary>
        /// Used to track the state of Webhooks
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<LinksElement?> _WebhooksOption { get; private set; }

        /// <summary>
        /// Gets or Sets Webhooks
        /// </summary>
        [JsonPropertyName("webhooks")]
        public LinksElement? Webhooks { get { return this._WebhooksOption; } set { this._WebhooksOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CompanyLinks {\n");
            sb.Append("  Self: ").Append(Self).Append("\n");
            sb.Append("  ApiCredentials: ").Append(ApiCredentials).Append("\n");
            sb.Append("  Users: ").Append(Users).Append("\n");
            sb.Append("  Webhooks: ").Append(Webhooks).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CompanyLinks" />
    /// </summary>
    public class CompanyLinksJsonConverter : JsonConverter<CompanyLinks>
    {
        /// <summary>
        /// Deserializes json to <see cref="CompanyLinks"/>.
        /// </summary>
        /// <param name="utf8JsonReader"><see cref="Utf8JsonReader"/>.</param>
        /// <param name="typeToConvert"><see cref="Type"/>.</param>
        /// <param name="jsonSerializerOptions">The <see cref="JsonSerializerOptions"/>, initialized from <see cref="HostConfiguration"/>.</param>
        /// <returns><see cref="CompanyLinks"/>.</returns>
        /// <exception cref="JsonException"></exception>
        public override CompanyLinks Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<LinksElement?> self = default;
            Option<LinksElement?> apiCredentials = default;
            Option<LinksElement?> users = default;
            Option<LinksElement?> webhooks = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? jsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (jsonPropertyName)
                    {
                        case "self":
                            self = new Option<LinksElement?>(JsonSerializer.Deserialize<LinksElement>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "apiCredentials":
                            apiCredentials = new Option<LinksElement?>(JsonSerializer.Deserialize<LinksElement>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "users":
                            users = new Option<LinksElement?>(JsonSerializer.Deserialize<LinksElement>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "webhooks":
                            webhooks = new Option<LinksElement?>(JsonSerializer.Deserialize<LinksElement>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }
            
            if (!self.IsSet)
                throw new ArgumentException("Property is required for class CompanyLinks.", nameof(self));

            return new CompanyLinks(self.Value!, apiCredentials, users, webhooks);
        }

        /// <summary>
        /// Serializes a <see cref="CompanyLinks"/>.
        /// </summary>
        /// <param name="writer"><see cref="Utf8JsonWriter"/></param>
        /// <param name="companyLinks"></param>
        /// <param name="jsonSerializerOptions"><see cref="JsonSerializerOptions"/></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CompanyLinks companyLinks, JsonSerializerOptions jsonSerializerOptions)
        {
            
            writer.WriteStartObject();
            
            WriteProperties(writer, companyLinks, jsonSerializerOptions);
            
            writer.WriteEndObject();
            
        }

        /// <summary>
        /// Serializes the properties of <see cref="CompanyLinks"/>.
        /// </summary>
        /// <param name="writer"><see creft="Utf8JsonWriter"/></param>
        /// <param name="companyLinks"></param>
        /// <param name="jsonSerializerOptions"><see cref="JsonSerializerOptions"/></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CompanyLinks companyLinks, JsonSerializerOptions jsonSerializerOptions)
        {
            
            writer.WritePropertyName("self");
            JsonSerializer.Serialize(writer, companyLinks.Self, jsonSerializerOptions);
            if (companyLinks._ApiCredentialsOption.IsSet)
            {
                writer.WritePropertyName("apiCredentials");
                JsonSerializer.Serialize(writer, companyLinks.ApiCredentials, jsonSerializerOptions);
            }
            if (companyLinks._UsersOption.IsSet)
            {
                writer.WritePropertyName("users");
                JsonSerializer.Serialize(writer, companyLinks.Users, jsonSerializerOptions);
            }
            if (companyLinks._WebhooksOption.IsSet)
            {
                writer.WritePropertyName("webhooks");
                JsonSerializer.Serialize(writer, companyLinks.Webhooks, jsonSerializerOptions);
            }
        }
    }
}
