// <auto-generated>
/*
 * Management API
 *
 * The version of the OpenAPI document: 3
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Adyen.Core;
using Adyen.Core.Converters;
using Adyen.Management.Client;

namespace Adyen.Management.Models
{
    /// <summary>
    /// InPersonDonationSettingsUpdate.
    /// </summary>
    [JsonConverter(typeof(InPersonDonationSettingsUpdateJsonConverter))]
    public partial class InPersonDonationSettingsUpdate
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InPersonDonationSettingsUpdate" /> class.
        /// </summary>
        public InPersonDonationSettingsUpdate()
        {
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// This is used to track if an optional field is set. If set, <see cref="DisplayTextField"/> will be populated.
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DisplayTextField?> _DisplayTextFieldOption { get; private set; }

        /// <summary>
        /// <see cref="DisplayTextField"/>.
        /// </summary>
        [JsonPropertyName("displayTextField")]
        public DisplayTextField? DisplayTextField { get { return this._DisplayTextFieldOption; } set { this._DisplayTextFieldOption = new(value); } }

        /// <summary>
        /// This is used to track if an optional field is set. If set, <see cref="DonationFlow"/> will be populated.
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DonationFlow?> _DonationFlowOption { get; private set; }

        /// <summary>
        /// <see cref="DonationFlow"/>.
        /// </summary>
        [JsonPropertyName("donationFlow")]
        public DonationFlow? DonationFlow { get { return this._DonationFlowOption; } set { this._DonationFlowOption = new(value); } }

        /// <summary>
        /// This is used to track if an optional field is set. If set, <see cref="DonationType"/> will be populated.
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DonationType?> _DonationTypeOption { get; private set; }

        /// <summary>
        /// <see cref="DonationType"/>.
        /// </summary>
        [JsonPropertyName("donationType")]
        public DonationType? DonationType { get { return this._DonationTypeOption; } set { this._DonationTypeOption = new(value); } }

        /// <summary>
        /// This is used to track if an optional field is set. If set, <see cref="DefaultAmount"/> will be populated.
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DonationAmountUpdate?> _DefaultAmountOption { get; private set; }

        /// <summary>
        /// <see cref="DefaultAmount"/>.
        /// </summary>
        [JsonPropertyName("defaultAmount")]
        public DonationAmountUpdate? DefaultAmount { get { return this._DefaultAmountOption; } set { this._DefaultAmountOption = new(value); } }

        /// <summary>
        /// This is used to track if an optional field is set. If set, <see cref="MerchantAccounts"/> will be populated.
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> _MerchantAccountsOption { get; private set; }

        /// <summary>
        /// The merchant accounts for this sales channel that are associated with the donation campaign.
        /// </summary>
        /// <value>The merchant accounts for this sales channel that are associated with the donation campaign.</value>
        [JsonPropertyName("merchantAccounts")]
        public List<string>? MerchantAccounts { get { return this._MerchantAccountsOption; } set { this._MerchantAccountsOption = new(value); } }

        /// <summary>
        /// This is used to track if an optional field is set. If set, <see cref="PresentCardTimeoutMs"/> will be populated.
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> _PresentCardTimeoutMsOption { get; private set; }

        /// <summary>
        /// Required if &#x60;donationFlow&#x60; is set to **twoStep**. The time, in milliseconds, that the terminal waits for the shopper to present their card. Defaults to **10000** (10 seconds). Range: 5000 to 15000.
        /// </summary>
        /// <value>Required if `donationFlow` is set to **twoStep**. The time, in milliseconds, that the terminal waits for the shopper to present their card. Defaults to **10000** (10 seconds). Range: 5000 to 15000.</value>
        [JsonPropertyName("presentCardTimeoutMs")]
        public Object? PresentCardTimeoutMs { get { return this._PresentCardTimeoutMsOption; } set { this._PresentCardTimeoutMsOption = new(value); } }

        /// <summary>
        /// This is used to track if an optional field is set. If set, <see cref="PromptTimeoutMs"/> will be populated.
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> _PromptTimeoutMsOption { get; private set; }

        /// <summary>
        /// The time, in milliseconds, that the terminal waits for the shopper to make a selection on the donation screen. Defaults to **10000** (10 seconds). Range: 5000 to 15000.
        /// </summary>
        /// <value>The time, in milliseconds, that the terminal waits for the shopper to make a selection on the donation screen. Defaults to **10000** (10 seconds). Range: 5000 to 15000.</value>
        [JsonPropertyName("promptTimeoutMs")]
        public Object? PromptTimeoutMs { get { return this._PromptTimeoutMsOption; } set { this._PromptTimeoutMsOption = new(value); } }

        /// <summary>
        /// This is used to track if an optional field is set. If set, <see cref="StoreIds"/> will be populated.
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> _StoreIdsOption { get; private set; }

        /// <summary>
        /// The Adyen-generated unique identifiers of stores for this sales channel that are associated with the donation campaign.
        /// </summary>
        /// <value>The Adyen-generated unique identifiers of stores for this sales channel that are associated with the donation campaign.</value>
        [JsonPropertyName("storeIds")]
        public List<string>? StoreIds { get { return this._StoreIdsOption; } set { this._StoreIdsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InPersonDonationSettingsUpdate {\n");
            sb.Append("  DefaultAmount: ").Append(DefaultAmount).Append("\n");
            sb.Append("  DisplayTextField: ").Append(DisplayTextField).Append("\n");
            sb.Append("  DonationFlow: ").Append(DonationFlow).Append("\n");
            sb.Append("  DonationType: ").Append(DonationType).Append("\n");
            sb.Append("  MerchantAccounts: ").Append(MerchantAccounts).Append("\n");
            sb.Append("  PresentCardTimeoutMs: ").Append(PresentCardTimeoutMs).Append("\n");
            sb.Append("  PromptTimeoutMs: ").Append(PromptTimeoutMs).Append("\n");
            sb.Append("  StoreIds: ").Append(StoreIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="InPersonDonationSettingsUpdate" />
    /// </summary>
    public class InPersonDonationSettingsUpdateJsonConverter : JsonConverter<InPersonDonationSettingsUpdate>
    {
        /// <summary>
        /// Deserializes json to <see cref="InPersonDonationSettingsUpdate"/>.
        /// </summary>
        /// <param name="utf8JsonReader"><see cref="Utf8JsonReader"/>.</param>
        /// <param name="typeToConvert"><see cref="Type"/>.</param>
        /// <param name="jsonSerializerOptions">The <see cref="JsonSerializerOptions"/>, initialized from <see cref="HostConfiguration"/>.</param>
        /// <returns><see cref="InPersonDonationSettingsUpdate"/>.</returns>
        /// <exception cref="JsonException"></exception>
        public override InPersonDonationSettingsUpdate Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<DonationAmountUpdate?> defaultAmount = default;
            Option<DisplayTextField?> displayTextField = default;
            Option<DonationFlow?> donationFlow = default;
            Option<DonationType?> donationType = default;
            Option<List<string>?> merchantAccounts = default;
            Option<Object?> presentCardTimeoutMs = default;
            Option<Object?> promptTimeoutMs = default;
            Option<List<string>?> storeIds = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? jsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (jsonPropertyName)
                    {
                        case "defaultAmount":
                            defaultAmount = new Option<DonationAmountUpdate?>(JsonSerializer.Deserialize<DonationAmountUpdate>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "displayTextField":
                            string? displayTextFieldRawValue = utf8JsonReader.GetString();
                            displayTextField = new Option<DisplayTextField?>(DisplayTextField.FromStringOrDefault(displayTextFieldRawValue) ?? (DisplayTextField)displayTextFieldRawValue);
                            break;
                        case "donationFlow":
                            string? donationFlowRawValue = utf8JsonReader.GetString();
                            donationFlow = new Option<DonationFlow?>(DonationFlow.FromStringOrDefault(donationFlowRawValue) ?? (DonationFlow)donationFlowRawValue);
                            break;
                        case "donationType":
                            string? donationTypeRawValue = utf8JsonReader.GetString();
                            donationType = new Option<DonationType?>(DonationType.FromStringOrDefault(donationTypeRawValue) ?? (DonationType)donationTypeRawValue);
                            break;
                        case "merchantAccounts":
                            merchantAccounts = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "presentCardTimeoutMs":
                            presentCardTimeoutMs = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "promptTimeoutMs":
                            promptTimeoutMs = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "storeIds":
                            storeIds = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }
            

            var inPersonDonationSettingsUpdate = new InPersonDonationSettingsUpdate();
            if (defaultAmount.IsSet)
                inPersonDonationSettingsUpdate.DefaultAmount = defaultAmount.Value;
            if (displayTextField.IsSet)
                inPersonDonationSettingsUpdate.DisplayTextField = displayTextField.Value;
            if (donationFlow.IsSet)
                inPersonDonationSettingsUpdate.DonationFlow = donationFlow.Value;
            if (donationType.IsSet)
                inPersonDonationSettingsUpdate.DonationType = donationType.Value;
            if (merchantAccounts.IsSet)
                inPersonDonationSettingsUpdate.MerchantAccounts = merchantAccounts.Value;
            if (presentCardTimeoutMs.IsSet)
                inPersonDonationSettingsUpdate.PresentCardTimeoutMs = presentCardTimeoutMs.Value;
            if (promptTimeoutMs.IsSet)
                inPersonDonationSettingsUpdate.PromptTimeoutMs = promptTimeoutMs.Value;
            if (storeIds.IsSet)
                inPersonDonationSettingsUpdate.StoreIds = storeIds.Value;
            return inPersonDonationSettingsUpdate;
        }

        /// <summary>
        /// Serializes a <see cref="InPersonDonationSettingsUpdate"/>.
        /// </summary>
        /// <param name="writer"><see cref="Utf8JsonWriter"/></param>
        /// <param name="inPersonDonationSettingsUpdate"></param>
        /// <param name="jsonSerializerOptions"><see cref="JsonSerializerOptions"/></param>
        public override void Write(Utf8JsonWriter writer, InPersonDonationSettingsUpdate inPersonDonationSettingsUpdate, JsonSerializerOptions jsonSerializerOptions)
        {
            
            writer.WriteStartObject();
            
            WriteProperties(writer, inPersonDonationSettingsUpdate, jsonSerializerOptions);
            
            writer.WriteEndObject();
            
        }

        /// <summary>
        /// Serializes the properties of <see cref="InPersonDonationSettingsUpdate"/>.
        /// </summary>
        /// <param name="writer"><see cref="Utf8JsonWriter"/></param>
        /// <param name="inPersonDonationSettingsUpdate"></param>
        /// <param name="jsonSerializerOptions"><see cref="JsonSerializerOptions"/></param>
        public void WriteProperties(Utf8JsonWriter writer, InPersonDonationSettingsUpdate inPersonDonationSettingsUpdate, JsonSerializerOptions jsonSerializerOptions)
        {
            
            if (inPersonDonationSettingsUpdate._DefaultAmountOption.IsSet)
                if (inPersonDonationSettingsUpdate._DefaultAmountOption.Value != null)
                {
                    writer.WritePropertyName("defaultAmount");
                    JsonSerializer.Serialize(writer, inPersonDonationSettingsUpdate.DefaultAmount, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("defaultAmount");
            if (inPersonDonationSettingsUpdate._DisplayTextFieldOption.IsSet)
            {
                var displayTextFieldRawValue = DisplayTextField.ToJsonValue(inPersonDonationSettingsUpdate.DisplayTextField);
                writer.WriteString("displayTextField", displayTextFieldRawValue);
            }
            if (inPersonDonationSettingsUpdate._DonationFlowOption.IsSet)
            {
                var donationFlowRawValue = DonationFlow.ToJsonValue(inPersonDonationSettingsUpdate.DonationFlow);
                writer.WriteString("donationFlow", donationFlowRawValue);
            }
            if (inPersonDonationSettingsUpdate._DonationTypeOption.IsSet)
                if (inPersonDonationSettingsUpdate._DonationTypeOption!.Value != null)
                {
                    var donationTypeRawValue = DonationType.ToJsonValue(inPersonDonationSettingsUpdate._DonationTypeOption.Value);
                    writer.WriteString("donationType", donationTypeRawValue);
                }
                else
                    writer.WriteNull("donationType");
            if (inPersonDonationSettingsUpdate._MerchantAccountsOption.IsSet)
            {
                writer.WritePropertyName("merchantAccounts");
                JsonSerializer.Serialize(writer, inPersonDonationSettingsUpdate.MerchantAccounts, jsonSerializerOptions);
            }
            if (inPersonDonationSettingsUpdate._PresentCardTimeoutMsOption.IsSet)
                if (inPersonDonationSettingsUpdate._PresentCardTimeoutMsOption.Value != null)
                {
                    writer.WritePropertyName("presentCardTimeoutMs");
                    JsonSerializer.Serialize(writer, inPersonDonationSettingsUpdate.PresentCardTimeoutMs, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("presentCardTimeoutMs");
            if (inPersonDonationSettingsUpdate._PromptTimeoutMsOption.IsSet)
                if (inPersonDonationSettingsUpdate._PromptTimeoutMsOption.Value != null)
                {
                    writer.WritePropertyName("promptTimeoutMs");
                    JsonSerializer.Serialize(writer, inPersonDonationSettingsUpdate.PromptTimeoutMs, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("promptTimeoutMs");
            if (inPersonDonationSettingsUpdate._StoreIdsOption.IsSet)
            {
                writer.WritePropertyName("storeIds");
                JsonSerializer.Serialize(writer, inPersonDonationSettingsUpdate.StoreIds, jsonSerializerOptions);
            }
        }
    }
}
