// <auto-generated>
/*
 * Management API
 *
 * Configure and manage your Adyen company and merchant accounts, stores, and payment terminals. ## Authentication Each request to the Management API must be signed with an API key. [Generate your API key](https://docs.adyen.com/development-resources/api-credentials#generate-api-key) in the Customer Area and then set this key to the `X-API-Key` header value.  To access the live endpoints, you need to generate a new API key in your live Customer Area. ## Versioning  Management API handles versioning as part of the endpoint URL. For example, to send a request to this version of the `/companies/{companyId}/webhooks` endpoint, use:  ```text https://management-test.adyen.com/v3/companies/{companyId}/webhooks ```  ## Going live  To access the live endpoints, you need an API key from your live Customer Area. Use this API key to make requests to:  ```text https://management-live.adyen.com/v3 ```  ## Release notes Have a look at the [release notes](https://docs.adyen.com/release-notes/management-api) to find out what changed in this version!
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Adyen.Core;
using Adyen.Management.Client;

namespace Adyen.Management.Models
{
    /// <summary>
    /// Merchant.
    /// </summary>
    public partial class Merchant : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Merchant" /> class.
        /// </summary>
        /// <param name="links">links</param>
        /// <param name="captureDelay">The [capture delay](https://docs.adyen.com/online-payments/capture#capture-delay) set for the merchant account.  Possible values: * **Immediate** * **Manual** * Number of days from **1** to **29**</param>
        /// <param name="companyId">The unique identifier of the company account this merchant belongs to</param>
        /// <param name="dataCenters">List of available data centers.  Adyen has several data centers around the world.In the URL that you use for making API requests, we recommend you use the live URL prefix from the data center closest to your shoppers.</param>
        /// <param name="defaultShopperInteraction">The default [&#x60;shopperInteraction&#x60;](https://docs.adyen.com/api-explorer/#/CheckoutService/v68/post/payments__reqParam_shopperInteraction) value used when processing payments through this merchant account.</param>
        /// <param name="description">Your description for the merchant account, maximum 300 characters</param>
        /// <param name="id">The unique identifier of the merchant account.</param>
        /// <param name="merchantCity">The city where the legal entity of this merchant account is registered.</param>
        /// <param name="name">The name of the legal entity associated with the merchant account.</param>
        /// <param name="pricingPlan">Only applies to merchant accounts managed by Adyen&#39;s partners. The name of the pricing plan assigned to the merchant account.</param>
        /// <param name="primarySettlementCurrency">The currency of the country where the legal entity of this merchant account is registered. Format: [ISO currency code](https://docs.adyen.com/development-resources/currency-codes). For example, a legal entity based in the United States has USD as the primary settlement currency.</param>
        /// <param name="reference">Reference of the merchant account.</param>
        /// <param name="shopWebAddress">The URL for the ecommerce website used with this merchant account.</param>
        /// <param name="status">The status of the merchant account.  Possible values:  * **PreActive**: The merchant account has been created. Users cannot access the merchant account in the Customer Area. The account cannot process payments. * **Active**: Users can access the merchant account in the Customer Area. If the company account is also **Active**, then payment processing and payouts are enabled. * **InactiveWithModifications**: Users can access the merchant account in the Customer Area. You cannot process new payments but you can still modify payments, for example issue refunds. You can still receive payouts. * **Inactive**: Users can access the merchant account in the Customer Area. Payment processing and payouts are disabled. * **Closed**: The account is closed and this cannot be reversed. Users cannot log in. Payment processing and payouts are disabled.</param>
        [JsonConstructor]
        public Merchant(Option<MerchantLinks?> links = default, Option<string?> captureDelay = default, Option<string?> companyId = default, Option<List<DataCenter>?> dataCenters = default, Option<string?> defaultShopperInteraction = default, Option<string?> description = default, Option<string?> id = default, Option<string?> merchantCity = default, Option<string?> name = default, Option<string?> pricingPlan = default, Option<string?> primarySettlementCurrency = default, Option<string?> reference = default, Option<string?> shopWebAddress = default, Option<string?> status = default)
        {
            _LinksOption = links;
            _CaptureDelayOption = captureDelay;
            _CompanyIdOption = companyId;
            _DataCentersOption = dataCenters;
            _DefaultShopperInteractionOption = defaultShopperInteraction;
            _DescriptionOption = description;
            _IdOption = id;
            _MerchantCityOption = merchantCity;
            _NameOption = name;
            _PricingPlanOption = pricingPlan;
            _PrimarySettlementCurrencyOption = primarySettlementCurrency;
            _ReferenceOption = reference;
            _ShopWebAddressOption = shopWebAddress;
            _StatusOption = status;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Links
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<MerchantLinks?> _LinksOption { get; private set; }

        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [JsonPropertyName("_links")]
        public MerchantLinks? Links { get { return this._LinksOption; } set { this._LinksOption = new(value); } }

        /// <summary>
        /// Used to track the state of CaptureDelay
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> _CaptureDelayOption { get; private set; }

        /// <summary>
        /// The [capture delay](https://docs.adyen.com/online-payments/capture#capture-delay) set for the merchant account.  Possible values: * **Immediate** * **Manual** * Number of days from **1** to **29**
        /// </summary>
        /// <value>The [capture delay](https://docs.adyen.com/online-payments/capture#capture-delay) set for the merchant account.  Possible values: * **Immediate** * **Manual** * Number of days from **1** to **29**</value>
        [JsonPropertyName("captureDelay")]
        public string? CaptureDelay { get { return this._CaptureDelayOption; } set { this._CaptureDelayOption = new(value); } }

        /// <summary>
        /// Used to track the state of CompanyId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> _CompanyIdOption { get; private set; }

        /// <summary>
        /// The unique identifier of the company account this merchant belongs to
        /// </summary>
        /// <value>The unique identifier of the company account this merchant belongs to</value>
        [JsonPropertyName("companyId")]
        public string? CompanyId { get { return this._CompanyIdOption; } set { this._CompanyIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of DataCenters
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<DataCenter>?> _DataCentersOption { get; private set; }

        /// <summary>
        /// List of available data centers.  Adyen has several data centers around the world.In the URL that you use for making API requests, we recommend you use the live URL prefix from the data center closest to your shoppers.
        /// </summary>
        /// <value>List of available data centers.  Adyen has several data centers around the world.In the URL that you use for making API requests, we recommend you use the live URL prefix from the data center closest to your shoppers.</value>
        [JsonPropertyName("dataCenters")]
        public List<DataCenter>? DataCenters { get { return this._DataCentersOption; } set { this._DataCentersOption = new(value); } }

        /// <summary>
        /// Used to track the state of DefaultShopperInteraction
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> _DefaultShopperInteractionOption { get; private set; }

        /// <summary>
        /// The default [&#x60;shopperInteraction&#x60;](https://docs.adyen.com/api-explorer/#/CheckoutService/v68/post/payments__reqParam_shopperInteraction) value used when processing payments through this merchant account.
        /// </summary>
        /// <value>The default [&#x60;shopperInteraction&#x60;](https://docs.adyen.com/api-explorer/#/CheckoutService/v68/post/payments__reqParam_shopperInteraction) value used when processing payments through this merchant account.</value>
        [JsonPropertyName("defaultShopperInteraction")]
        public string? DefaultShopperInteraction { get { return this._DefaultShopperInteractionOption; } set { this._DefaultShopperInteractionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> _DescriptionOption { get; private set; }

        /// <summary>
        /// Your description for the merchant account, maximum 300 characters
        /// </summary>
        /// <value>Your description for the merchant account, maximum 300 characters</value>
        [JsonPropertyName("description")]
        public string? Description { get { return this._DescriptionOption; } set { this._DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> _IdOption { get; private set; }

        /// <summary>
        /// The unique identifier of the merchant account.
        /// </summary>
        /// <value>The unique identifier of the merchant account.</value>
        [JsonPropertyName("id")]
        public string? Id { get { return this._IdOption; } set { this._IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of MerchantCity
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> _MerchantCityOption { get; private set; }

        /// <summary>
        /// The city where the legal entity of this merchant account is registered.
        /// </summary>
        /// <value>The city where the legal entity of this merchant account is registered.</value>
        [JsonPropertyName("merchantCity")]
        public string? MerchantCity { get { return this._MerchantCityOption; } set { this._MerchantCityOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> _NameOption { get; private set; }

        /// <summary>
        /// The name of the legal entity associated with the merchant account.
        /// </summary>
        /// <value>The name of the legal entity associated with the merchant account.</value>
        [JsonPropertyName("name")]
        public string? Name { get { return this._NameOption; } set { this._NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of PricingPlan
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> _PricingPlanOption { get; private set; }

        /// <summary>
        /// Only applies to merchant accounts managed by Adyen&#39;s partners. The name of the pricing plan assigned to the merchant account.
        /// </summary>
        /// <value>Only applies to merchant accounts managed by Adyen&#39;s partners. The name of the pricing plan assigned to the merchant account.</value>
        [JsonPropertyName("pricingPlan")]
        public string? PricingPlan { get { return this._PricingPlanOption; } set { this._PricingPlanOption = new(value); } }

        /// <summary>
        /// Used to track the state of PrimarySettlementCurrency
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> _PrimarySettlementCurrencyOption { get; private set; }

        /// <summary>
        /// The currency of the country where the legal entity of this merchant account is registered. Format: [ISO currency code](https://docs.adyen.com/development-resources/currency-codes). For example, a legal entity based in the United States has USD as the primary settlement currency.
        /// </summary>
        /// <value>The currency of the country where the legal entity of this merchant account is registered. Format: [ISO currency code](https://docs.adyen.com/development-resources/currency-codes). For example, a legal entity based in the United States has USD as the primary settlement currency.</value>
        [JsonPropertyName("primarySettlementCurrency")]
        public string? PrimarySettlementCurrency { get { return this._PrimarySettlementCurrencyOption; } set { this._PrimarySettlementCurrencyOption = new(value); } }

        /// <summary>
        /// Used to track the state of Reference
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> _ReferenceOption { get; private set; }

        /// <summary>
        /// Reference of the merchant account.
        /// </summary>
        /// <value>Reference of the merchant account.</value>
        [JsonPropertyName("reference")]
        public string? Reference { get { return this._ReferenceOption; } set { this._ReferenceOption = new(value); } }

        /// <summary>
        /// Used to track the state of ShopWebAddress
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> _ShopWebAddressOption { get; private set; }

        /// <summary>
        /// The URL for the ecommerce website used with this merchant account.
        /// </summary>
        /// <value>The URL for the ecommerce website used with this merchant account.</value>
        [JsonPropertyName("shopWebAddress")]
        public string? ShopWebAddress { get { return this._ShopWebAddressOption; } set { this._ShopWebAddressOption = new(value); } }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> _StatusOption { get; private set; }

        /// <summary>
        /// The status of the merchant account.  Possible values:  * **PreActive**: The merchant account has been created. Users cannot access the merchant account in the Customer Area. The account cannot process payments. * **Active**: Users can access the merchant account in the Customer Area. If the company account is also **Active**, then payment processing and payouts are enabled. * **InactiveWithModifications**: Users can access the merchant account in the Customer Area. You cannot process new payments but you can still modify payments, for example issue refunds. You can still receive payouts. * **Inactive**: Users can access the merchant account in the Customer Area. Payment processing and payouts are disabled. * **Closed**: The account is closed and this cannot be reversed. Users cannot log in. Payment processing and payouts are disabled.
        /// </summary>
        /// <value>The status of the merchant account.  Possible values:  * **PreActive**: The merchant account has been created. Users cannot access the merchant account in the Customer Area. The account cannot process payments. * **Active**: Users can access the merchant account in the Customer Area. If the company account is also **Active**, then payment processing and payouts are enabled. * **InactiveWithModifications**: Users can access the merchant account in the Customer Area. You cannot process new payments but you can still modify payments, for example issue refunds. You can still receive payouts. * **Inactive**: Users can access the merchant account in the Customer Area. Payment processing and payouts are disabled. * **Closed**: The account is closed and this cannot be reversed. Users cannot log in. Payment processing and payouts are disabled.</value>
        [JsonPropertyName("status")]
        public string? Status { get { return this._StatusOption; } set { this._StatusOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Merchant {\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("  CaptureDelay: ").Append(CaptureDelay).Append("\n");
            sb.Append("  CompanyId: ").Append(CompanyId).Append("\n");
            sb.Append("  DataCenters: ").Append(DataCenters).Append("\n");
            sb.Append("  DefaultShopperInteraction: ").Append(DefaultShopperInteraction).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  MerchantCity: ").Append(MerchantCity).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  PricingPlan: ").Append(PricingPlan).Append("\n");
            sb.Append("  PrimarySettlementCurrency: ").Append(PrimarySettlementCurrency).Append("\n");
            sb.Append("  Reference: ").Append(Reference).Append("\n");
            sb.Append("  ShopWebAddress: ").Append(ShopWebAddress).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Merchant" />
    /// </summary>
    public class MerchantJsonConverter : JsonConverter<Merchant>
    {
        /// <summary>
        /// Deserializes json to <see cref="Merchant"/>.
        /// </summary>
        /// <param name="utf8JsonReader"><see cref="Utf8JsonReader"/></param>
        /// <param name="typeToConvert"><see cref="Type"/></param>
        /// <param name="jsonSerializerOptions">The <see cref="JsonSerializerOptions"/>, initialized from <see cref="HostConfiguration"/>.</param>
        /// <returns><see cref="Merchant"/></returns>
        /// <exception cref="JsonException"></exception>
        public override Merchant Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<MerchantLinks?> links = default;
            Option<string?> captureDelay = default;
            Option<string?> companyId = default;
            Option<List<DataCenter>?> dataCenters = default;
            Option<string?> defaultShopperInteraction = default;
            Option<string?> description = default;
            Option<string?> id = default;
            Option<string?> merchantCity = default;
            Option<string?> name = default;
            Option<string?> pricingPlan = default;
            Option<string?> primarySettlementCurrency = default;
            Option<string?> reference = default;
            Option<string?> shopWebAddress = default;
            Option<string?> status = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? jsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (jsonPropertyName)
                    {
                        case "_links":
                            links = new Option<MerchantLinks?>(JsonSerializer.Deserialize<MerchantLinks>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "captureDelay":
                            captureDelay = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "companyId":
                            companyId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "dataCenters":
                            dataCenters = new Option<List<DataCenter>?>(JsonSerializer.Deserialize<List<DataCenter>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "defaultShopperInteraction":
                            defaultShopperInteraction = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "merchantCity":
                            merchantCity = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "pricingPlan":
                            pricingPlan = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "primarySettlementCurrency":
                            primarySettlementCurrency = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "reference":
                            reference = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "shopWebAddress":
                            shopWebAddress = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }
            
            if (links.IsSet && links.Value == null)
                throw new ArgumentNullException(nameof(links), "Property is not nullable for class Merchant.");

            if (captureDelay.IsSet && captureDelay.Value == null)
                throw new ArgumentNullException(nameof(captureDelay), "Property is not nullable for class Merchant.");

            if (companyId.IsSet && companyId.Value == null)
                throw new ArgumentNullException(nameof(companyId), "Property is not nullable for class Merchant.");

            if (dataCenters.IsSet && dataCenters.Value == null)
                throw new ArgumentNullException(nameof(dataCenters), "Property is not nullable for class Merchant.");

            if (defaultShopperInteraction.IsSet && defaultShopperInteraction.Value == null)
                throw new ArgumentNullException(nameof(defaultShopperInteraction), "Property is not nullable for class Merchant.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class Merchant.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class Merchant.");

            if (merchantCity.IsSet && merchantCity.Value == null)
                throw new ArgumentNullException(nameof(merchantCity), "Property is not nullable for class Merchant.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class Merchant.");

            if (pricingPlan.IsSet && pricingPlan.Value == null)
                throw new ArgumentNullException(nameof(pricingPlan), "Property is not nullable for class Merchant.");

            if (primarySettlementCurrency.IsSet && primarySettlementCurrency.Value == null)
                throw new ArgumentNullException(nameof(primarySettlementCurrency), "Property is not nullable for class Merchant.");

            if (reference.IsSet && reference.Value == null)
                throw new ArgumentNullException(nameof(reference), "Property is not nullable for class Merchant.");

            if (shopWebAddress.IsSet && shopWebAddress.Value == null)
                throw new ArgumentNullException(nameof(shopWebAddress), "Property is not nullable for class Merchant.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class Merchant.");

            return new Merchant(links, captureDelay, companyId, dataCenters, defaultShopperInteraction, description, id, merchantCity, name, pricingPlan, primarySettlementCurrency, reference, shopWebAddress, status);
        }

        /// <summary>
        /// Serializes a <see cref="Merchant"/>.
        /// </summary>
        /// <param name="writer"><see cref="Utf8JsonWriter"/></param>
        /// <param name="merchant"></param>
        /// <param name="jsonSerializerOptions"><see cref="JsonSerializerOptions"/></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Merchant merchant, JsonSerializerOptions jsonSerializerOptions)
        {
            
            writer.WriteStartObject();
            
            WriteProperties(writer, merchant, jsonSerializerOptions);
            
            writer.WriteEndObject();
            
        }

        /// <summary>
        /// Serializes the properties of <see cref="Merchant"/>.
        /// </summary>
        /// <param name="writer"><see creft="Utf8JsonWriter"/></param>
        /// <param name="merchant"></param>
        /// <param name="jsonSerializerOptions"><see cref="JsonSerializerOptions"/></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Merchant merchant, JsonSerializerOptions jsonSerializerOptions)
        {
            /*
            if (merchant._LinksOption.IsSet && merchant.Links == null)
                throw new ArgumentNullException(nameof(merchant.Links), "Property is required for class Merchant.");

            if (merchant._CaptureDelayOption.IsSet && merchant.CaptureDelay == null)
                throw new ArgumentNullException(nameof(merchant.CaptureDelay), "Property is required for class Merchant.");

            if (merchant._CompanyIdOption.IsSet && merchant.CompanyId == null)
                throw new ArgumentNullException(nameof(merchant.CompanyId), "Property is required for class Merchant.");

            if (merchant._DataCentersOption.IsSet && merchant.DataCenters == null)
                throw new ArgumentNullException(nameof(merchant.DataCenters), "Property is required for class Merchant.");

            if (merchant._DefaultShopperInteractionOption.IsSet && merchant.DefaultShopperInteraction == null)
                throw new ArgumentNullException(nameof(merchant.DefaultShopperInteraction), "Property is required for class Merchant.");

            if (merchant._DescriptionOption.IsSet && merchant.Description == null)
                throw new ArgumentNullException(nameof(merchant.Description), "Property is required for class Merchant.");

            if (merchant._IdOption.IsSet && merchant.Id == null)
                throw new ArgumentNullException(nameof(merchant.Id), "Property is required for class Merchant.");

            if (merchant._MerchantCityOption.IsSet && merchant.MerchantCity == null)
                throw new ArgumentNullException(nameof(merchant.MerchantCity), "Property is required for class Merchant.");

            if (merchant._NameOption.IsSet && merchant.Name == null)
                throw new ArgumentNullException(nameof(merchant.Name), "Property is required for class Merchant.");

            if (merchant._PricingPlanOption.IsSet && merchant.PricingPlan == null)
                throw new ArgumentNullException(nameof(merchant.PricingPlan), "Property is required for class Merchant.");

            if (merchant._PrimarySettlementCurrencyOption.IsSet && merchant.PrimarySettlementCurrency == null)
                throw new ArgumentNullException(nameof(merchant.PrimarySettlementCurrency), "Property is required for class Merchant.");

            if (merchant._ReferenceOption.IsSet && merchant.Reference == null)
                throw new ArgumentNullException(nameof(merchant.Reference), "Property is required for class Merchant.");

            if (merchant._ShopWebAddressOption.IsSet && merchant.ShopWebAddress == null)
                throw new ArgumentNullException(nameof(merchant.ShopWebAddress), "Property is required for class Merchant.");

            if (merchant._StatusOption.IsSet && merchant.Status == null)
                throw new ArgumentNullException(nameof(merchant.Status), "Property is required for class Merchant.");

            */
            
            if (merchant._LinksOption.IsSet)
            {
                writer.WritePropertyName("_links");
                JsonSerializer.Serialize(writer, merchant.Links, jsonSerializerOptions);
            }
            if (merchant._CaptureDelayOption.IsSet)
                writer.WriteString("captureDelay", merchant.CaptureDelay);

            if (merchant._CompanyIdOption.IsSet)
                writer.WriteString("companyId", merchant.CompanyId);

            if (merchant._DataCentersOption.IsSet)
            {
                writer.WritePropertyName("dataCenters");
                JsonSerializer.Serialize(writer, merchant.DataCenters, jsonSerializerOptions);
            }
            if (merchant._DefaultShopperInteractionOption.IsSet)
                writer.WriteString("defaultShopperInteraction", merchant.DefaultShopperInteraction);

            if (merchant._DescriptionOption.IsSet)
                writer.WriteString("description", merchant.Description);

            if (merchant._IdOption.IsSet)
                writer.WriteString("id", merchant.Id);

            if (merchant._MerchantCityOption.IsSet)
                writer.WriteString("merchantCity", merchant.MerchantCity);

            if (merchant._NameOption.IsSet)
                writer.WriteString("name", merchant.Name);

            if (merchant._PricingPlanOption.IsSet)
                writer.WriteString("pricingPlan", merchant.PricingPlan);

            if (merchant._PrimarySettlementCurrencyOption.IsSet)
                writer.WriteString("primarySettlementCurrency", merchant.PrimarySettlementCurrency);

            if (merchant._ReferenceOption.IsSet)
                writer.WriteString("reference", merchant.Reference);

            if (merchant._ShopWebAddressOption.IsSet)
                writer.WriteString("shopWebAddress", merchant.ShopWebAddress);

            if (merchant._StatusOption.IsSet)
                writer.WriteString("status", merchant.Status);
        }
    }
}
