name: .NET Core

on: [push, pull_request]

jobs:
  build:
    name: Build and test

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            2.1.x
            3.1.x
            5.0.x
            6.0.x
      - name: Install tools
        run: |
          dotnet restore
      
      - name: Build Debug
        run: dotnet build -c Debug    
        
      - name: Run test suite netcoreapp2.1
        run: dotnet test --no-build -c Debug -f netcoreapp2.1 Adyen.Test/Adyen.Test.csproj 
        
      - name: Run test suite netcoreapp3.1
        run: dotnet test --no-build -c Debug -f netcoreapp3.1 Adyen.Test/Adyen.Test.csproj 
        
      - name: Run test suite net5.0
        run: dotnet test --no-build -c Debug -f net5.0 Adyen.Test/Adyen.Test.csproj         
      
      - name: Run test suite net6.0
        run: dotnet test --no-build -c Debug -f net6.0 Adyen.Test/Adyen.Test.csproj  
        
        
        
