name: .NET Core

on: [ workflow_dispatch ]

jobs:
  build:
    name: Build and test

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            2.1.x
      - name: Install tools
        run: |
          dotnet restore

      - name: Build Debug
        run: dotnet build -c Debug

      - name: Run test suite netcoreapp2.1
        run: dotnet test --no-build -c Debug -f netcoreapp2.1 Adyen.Test/Adyen.Test.csproj /p:Framework=netcoreapp2.1

      - name: Run integration test suite netcoreapp2.1
        run: dotnet test --no-build -c Debug -f netcoreapp2.1 Adyen.IntegrationTest/Adyen.IntegrationTest.csproj
        if: ${{ github.event.pull_request.head.ref == 'main' }}
