name: .NET Core

on:
  push:
    branches:
      - main
      - sdk-automation/models
      - promote/main
  pull_request:
    branches:
      - main
      - sdk-automation/models
      - promote/main
  workflow_dispatch: {}

jobs:
  build-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet-version: ['6.0.x']

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
            
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build Debug
        run: dotnet build -c Debug
        
      - name: Run unit tests
        run: dotnet test --no-build -c Debug -f net6.0 Adyen.Test/Adyen.Test.csproj

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: build-test
    if: |
      github.event_name == 'pull_request' &&
      contains(github.event.pull_request.labels.*.name, 'release') &&
      github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
          
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
            
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build Debug
        run: dotnet build -c Debug
        
      - name: Run integration tests
        run: dotnet test --no-build -c Debug -f net6.0 Adyen.IntegrationTest/Adyen.IntegrationTest.csproj