name: Automatic Github release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  gh_release:
    permissions:
      contents: write
    uses: Adyen/release-automation-action/.github/workflows/reusable-github-release.yml@v1.1.1
    with:
      release-title: Adyen .NET API Library 
      develop-branch: develop
      release-branch: main
    secrets:
      token: ${{ secrets.ADYEN_AUTOMATION_BOT_ACCESS_TOKEN }}