on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string

jobs:
  gh_release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ADYEN_AUTOMATION_BOT_ACCESS_TOKEN }}
      - name: Grab current version
        id: current-version
        run: make version
      - name: Create new release
        env:
          GH_TOKEN: ${{ secrets.ADYEN_AUTOMATION_BOT_ACCESS_TOKEN }}
        run: |
          gh release create v${{steps.current-version.outputs.currentVersion}} \
            --title 'Adyen ${{ inputs.project-name }} API Library v${{steps.current-version.outputs.currentVersion}}' \
            --generate-notes --target main
      - name: Update develop branch
        run: |
          git checkout develop
          git merge origin/main
          git push origin develop