name: Publish to NuGet

on:
  release:
    types: [published]

jobs:
  # publish the nuget package
  publish:
    name: Build, Pack & Publish
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v4
      
      # Sets up .NET 
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      # Build Release and test
      - name: Build Release
        run: dotnet build Adyen -c Release

      - name: Run unit tests on net8.0
        run: dotnet test --no-build -c Release -f net8.0 Adyen.Test/Adyen.Test.csproj

      # Pack Release
      - name: Pack
        run: dotnet pack Adyen --no-build --configuration Release --output nuget

      # Publish Package
      - name: Publish Nuget
        run: dotnet nuget push nuget/*.nupkg --api-key ${{ secrets.ADYEN_NUGET }} --source "nuget.org"