// <auto-generated>
/*
 * Adyen Checkout API
 *
 * Adyen Checkout API provides a simple and flexible way to initiate and authorise online payments. You can use the same integration for payments made with cards (including 3D Secure), mobile wallets, and local payment methods (for example, iDEAL and Sofort).  This API reference provides information on available endpoints and how to interact with them. To learn more about the API, visit [online payments documentation](https://docs.adyen.com/online-payments).  ## Authentication Each request to Checkout API must be signed with an API key. For this, [get your API key](https://docs.adyen.com/development-resources/api-credentials#generate-api-key) from your Customer Area, and set this key to the `X-API-Key` header value, for example:  ``` curl -H \"Content-Type: application/json\" \\ -H \"X-API-Key: YOUR_API_KEY\" \\ ... ``` ## Versioning Checkout API supports [versioning](https://docs.adyen.com/development-resources/versioning) using a version suffix in the endpoint URL. This suffix has the following format: \"vXX\", where XX is the version number.  For example: ``` https://checkout-test.adyen.com/v71/payments ```  ## Going live  To access the live endpoints, you need an API key from your live Customer Area.  The live endpoint URLs contain a prefix which is unique to your company account, for example: ``` https://{PREFIX}-checkout-live.adyenpayments.com/checkout/v71/payments ```  Get your `{PREFIX}` from your live Customer Area under **Developers** > **API URLs** > **Prefix**.  When preparing to do live transactions with Checkout API, follow the [go-live checklist](https://docs.adyen.com/online-payments/go-live-checklist) to make sure you've got all the required configuration in place.  ## Release notes Have a look at the [release notes](https://docs.adyen.com/online-payments/release-notes?integration_type=api&version=71) to find out what changed in this version!
 *
 * The version of the OpenAPI document: 71
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Adyen.Client;

namespace Adyen.Model.Checkout
{
    /// <summary>
    /// CheckoutThreeDS2Action
    /// </summary>
    public partial class CheckoutThreeDS2Action : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckoutThreeDS2Action" /> class.
        /// </summary>
        /// <param name="type">**threeDS2**</param>
        /// <param name="authorisationToken">A token needed to authorise a payment.</param>
        /// <param name="paymentData">Encoded payment data.</param>
        /// <param name="paymentMethodType">Specifies the payment method.</param>
        /// <param name="subtype">A subtype of the token.</param>
        /// <param name="token">A token to pass to the 3DS2 Component to get the fingerprint.</param>
        /// <param name="url">Specifies the URL to redirect to.</param>
        [JsonConstructor]
        public CheckoutThreeDS2Action(TypeEnum type, Option<string> authorisationToken = default, Option<string> paymentData = default, Option<string> paymentMethodType = default, Option<string> subtype = default, Option<string> token = default, Option<string> url = default)
        {
            Type = type;
            AuthorisationTokenOption = authorisationToken;
            PaymentDataOption = paymentData;
            PaymentMethodTypeOption = paymentMethodType;
            SubtypeOption = subtype;
            TokenOption = token;
            UrlOption = url;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// **threeDS2**
        /// </summary>
        /// <value>**threeDS2**</value>
        public enum TypeEnum
        {
            /// <summary>
            /// Enum ThreeDS2 for value: threeDS2
            /// </summary>
            ThreeDS2 = 1
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TypeEnum TypeEnumFromString(string value)
        {
            if (value.Equals("threeDS2"))
                return TypeEnum.ThreeDS2;

            throw new NotImplementedException($"Could not convert value to type TypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TypeEnum? TypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("threeDS2"))
                return TypeEnum.ThreeDS2;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TypeEnumToJsonValue(TypeEnum value)
        {
            if (value == TypeEnum.ThreeDS2)
                return "threeDS2";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// **threeDS2**
        /// </summary>
        /// <value>**threeDS2**</value>
        [JsonPropertyName("type")]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Used to track the state of AuthorisationToken
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> AuthorisationTokenOption { get; private set; }

        /// <summary>
        /// A token needed to authorise a payment.
        /// </summary>
        /// <value>A token needed to authorise a payment.</value>
        [JsonPropertyName("authorisationToken")]
        public string AuthorisationToken { get { return this.AuthorisationTokenOption; } set { this.AuthorisationTokenOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of PaymentData
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> PaymentDataOption { get; private set; }

        /// <summary>
        /// Encoded payment data.
        /// </summary>
        /// <value>Encoded payment data.</value>
        [JsonPropertyName("paymentData")]
        public string PaymentData { get { return this.PaymentDataOption; } set { this.PaymentDataOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of PaymentMethodType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> PaymentMethodTypeOption { get; private set; }

        /// <summary>
        /// Specifies the payment method.
        /// </summary>
        /// <value>Specifies the payment method.</value>
        [JsonPropertyName("paymentMethodType")]
        public string PaymentMethodType { get { return this.PaymentMethodTypeOption; } set { this.PaymentMethodTypeOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Subtype
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> SubtypeOption { get; private set; }

        /// <summary>
        /// A subtype of the token.
        /// </summary>
        /// <value>A subtype of the token.</value>
        [JsonPropertyName("subtype")]
        public string Subtype { get { return this.SubtypeOption; } set { this.SubtypeOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Token
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> TokenOption { get; private set; }

        /// <summary>
        /// A token to pass to the 3DS2 Component to get the fingerprint.
        /// </summary>
        /// <value>A token to pass to the 3DS2 Component to get the fingerprint.</value>
        [JsonPropertyName("token")]
        public string Token { get { return this.TokenOption; } set { this.TokenOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Url
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> UrlOption { get; private set; }

        /// <summary>
        /// Specifies the URL to redirect to.
        /// </summary>
        /// <value>Specifies the URL to redirect to.</value>
        [JsonPropertyName("url")]
        public string Url { get { return this.UrlOption; } set { this.UrlOption = new Option<string>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CheckoutThreeDS2Action {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  AuthorisationToken: ").Append(AuthorisationToken).Append("\n");
            sb.Append("  PaymentData: ").Append(PaymentData).Append("\n");
            sb.Append("  PaymentMethodType: ").Append(PaymentMethodType).Append("\n");
            sb.Append("  Subtype: ").Append(Subtype).Append("\n");
            sb.Append("  Token: ").Append(Token).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CheckoutThreeDS2Action" />
    /// </summary>
    public class CheckoutThreeDS2ActionJsonConverter : JsonConverter<CheckoutThreeDS2Action>
    {
        /// <summary>
        /// Deserializes json to <see cref="CheckoutThreeDS2Action" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CheckoutThreeDS2Action Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<CheckoutThreeDS2Action.TypeEnum?> type = default;
            Option<string> authorisationToken = default;
            Option<string> paymentData = default;
            Option<string> paymentMethodType = default;
            Option<string> subtype = default;
            Option<string> token = default;
            Option<string> url = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "type":
                            string typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<CheckoutThreeDS2Action.TypeEnum?>(CheckoutThreeDS2Action.TypeEnumFromStringOrDefault(typeRawValue));
                            break;
                        case "authorisationToken":
                            authorisationToken = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "paymentData":
                            paymentData = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "paymentMethodType":
                            paymentMethodType = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "subtype":
                            subtype = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "token":
                            token = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "url":
                            url = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class CheckoutThreeDS2Action.", nameof(type));

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class CheckoutThreeDS2Action.");

            if (authorisationToken.IsSet && authorisationToken.Value == null)
                throw new ArgumentNullException(nameof(authorisationToken), "Property is not nullable for class CheckoutThreeDS2Action.");

            if (paymentData.IsSet && paymentData.Value == null)
                throw new ArgumentNullException(nameof(paymentData), "Property is not nullable for class CheckoutThreeDS2Action.");

            if (paymentMethodType.IsSet && paymentMethodType.Value == null)
                throw new ArgumentNullException(nameof(paymentMethodType), "Property is not nullable for class CheckoutThreeDS2Action.");

            if (subtype.IsSet && subtype.Value == null)
                throw new ArgumentNullException(nameof(subtype), "Property is not nullable for class CheckoutThreeDS2Action.");

            if (token.IsSet && token.Value == null)
                throw new ArgumentNullException(nameof(token), "Property is not nullable for class CheckoutThreeDS2Action.");

            if (url.IsSet && url.Value == null)
                throw new ArgumentNullException(nameof(url), "Property is not nullable for class CheckoutThreeDS2Action.");

            return new CheckoutThreeDS2Action(type.Value.Value, authorisationToken, paymentData, paymentMethodType, subtype, token, url);
        }

        /// <summary>
        /// Serializes a <see cref="CheckoutThreeDS2Action" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="checkoutThreeDS2Action"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CheckoutThreeDS2Action checkoutThreeDS2Action, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, checkoutThreeDS2Action, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CheckoutThreeDS2Action" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="checkoutThreeDS2Action"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CheckoutThreeDS2Action checkoutThreeDS2Action, JsonSerializerOptions jsonSerializerOptions)
        {
            if (checkoutThreeDS2Action.AuthorisationTokenOption.IsSet && checkoutThreeDS2Action.AuthorisationToken == null)
                throw new ArgumentNullException(nameof(checkoutThreeDS2Action.AuthorisationToken), "Property is required for class CheckoutThreeDS2Action.");

            if (checkoutThreeDS2Action.PaymentDataOption.IsSet && checkoutThreeDS2Action.PaymentData == null)
                throw new ArgumentNullException(nameof(checkoutThreeDS2Action.PaymentData), "Property is required for class CheckoutThreeDS2Action.");

            if (checkoutThreeDS2Action.PaymentMethodTypeOption.IsSet && checkoutThreeDS2Action.PaymentMethodType == null)
                throw new ArgumentNullException(nameof(checkoutThreeDS2Action.PaymentMethodType), "Property is required for class CheckoutThreeDS2Action.");

            if (checkoutThreeDS2Action.SubtypeOption.IsSet && checkoutThreeDS2Action.Subtype == null)
                throw new ArgumentNullException(nameof(checkoutThreeDS2Action.Subtype), "Property is required for class CheckoutThreeDS2Action.");

            if (checkoutThreeDS2Action.TokenOption.IsSet && checkoutThreeDS2Action.Token == null)
                throw new ArgumentNullException(nameof(checkoutThreeDS2Action.Token), "Property is required for class CheckoutThreeDS2Action.");

            if (checkoutThreeDS2Action.UrlOption.IsSet && checkoutThreeDS2Action.Url == null)
                throw new ArgumentNullException(nameof(checkoutThreeDS2Action.Url), "Property is required for class CheckoutThreeDS2Action.");

            var typeRawValue = CheckoutThreeDS2Action.TypeEnumToJsonValue(checkoutThreeDS2Action.Type);
            writer.WriteString("type", typeRawValue);
            if (checkoutThreeDS2Action.AuthorisationTokenOption.IsSet)
                writer.WriteString("authorisationToken", checkoutThreeDS2Action.AuthorisationToken);

            if (checkoutThreeDS2Action.PaymentDataOption.IsSet)
                writer.WriteString("paymentData", checkoutThreeDS2Action.PaymentData);

            if (checkoutThreeDS2Action.PaymentMethodTypeOption.IsSet)
                writer.WriteString("paymentMethodType", checkoutThreeDS2Action.PaymentMethodType);

            if (checkoutThreeDS2Action.SubtypeOption.IsSet)
                writer.WriteString("subtype", checkoutThreeDS2Action.Subtype);

            if (checkoutThreeDS2Action.TokenOption.IsSet)
                writer.WriteString("token", checkoutThreeDS2Action.Token);

            if (checkoutThreeDS2Action.UrlOption.IsSet)
                writer.WriteString("url", checkoutThreeDS2Action.Url);
        }
    }
}
