/*
* Adyen Checkout API
*
*
* The version of the OpenAPI document: 71
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Adyen.ApiSerialization.OpenAPIDateConverter;

namespace Adyen.Model.Checkout
{
    /// <summary>
    /// PayToDetails
    /// </summary>
    [DataContract(Name = "PayToDetails")]
    public partial class PayToDetails : IEquatable<PayToDetails>, IValidatableObject
    {
        /// <summary>
        /// **payto**
        /// </summary>
        /// <value>**payto**</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Payto for value: payto
            /// </summary>
            [EnumMember(Value = "payto")]
            Payto = 1

        }


        /// <summary>
        /// **payto**
        /// </summary>
        /// <value>**payto**</value>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public TypeEnum? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PayToDetails" /> class.
        /// </summary>
        /// <param name="checkoutAttemptId">The checkout attempt identifier..</param>
        /// <param name="shopperAccountIdentifier">The shopper&#39;s banking details or payId reference, used to complete payment..</param>
        /// <param name="type">**payto** (default to TypeEnum.Payto).</param>
        public PayToDetails(string checkoutAttemptId = default(string), string shopperAccountIdentifier = default(string), TypeEnum? type = TypeEnum.Payto)
        {
            this.CheckoutAttemptId = checkoutAttemptId;
            this.ShopperAccountIdentifier = shopperAccountIdentifier;
            this.Type = type;
        }

        /// <summary>
        /// The checkout attempt identifier.
        /// </summary>
        /// <value>The checkout attempt identifier.</value>
        [DataMember(Name = "checkoutAttemptId", EmitDefaultValue = false)]
        public string CheckoutAttemptId { get; set; }

        /// <summary>
        /// The shopper&#39;s banking details or payId reference, used to complete payment.
        /// </summary>
        /// <value>The shopper&#39;s banking details or payId reference, used to complete payment.</value>
        [DataMember(Name = "shopperAccountIdentifier", EmitDefaultValue = false)]
        public string ShopperAccountIdentifier { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PayToDetails {\n");
            sb.Append("  CheckoutAttemptId: ").Append(CheckoutAttemptId).Append("\n");
            sb.Append("  ShopperAccountIdentifier: ").Append(ShopperAccountIdentifier).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PayToDetails);
        }

        /// <summary>
        /// Returns true if PayToDetails instances are equal
        /// </summary>
        /// <param name="input">Instance of PayToDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PayToDetails input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.CheckoutAttemptId == input.CheckoutAttemptId ||
                    (this.CheckoutAttemptId != null &&
                    this.CheckoutAttemptId.Equals(input.CheckoutAttemptId))
                ) && 
                (
                    this.ShopperAccountIdentifier == input.ShopperAccountIdentifier ||
                    (this.ShopperAccountIdentifier != null &&
                    this.ShopperAccountIdentifier.Equals(input.ShopperAccountIdentifier))
                ) && 
                (
                    this.Type == input.Type ||
                    this.Type.Equals(input.Type)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CheckoutAttemptId != null)
                {
                    hashCode = (hashCode * 59) + this.CheckoutAttemptId.GetHashCode();
                }
                if (this.ShopperAccountIdentifier != null)
                {
                    hashCode = (hashCode * 59) + this.ShopperAccountIdentifier.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Type.GetHashCode();
                return hashCode;
            }
        }
        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
