// <auto-generated>
/*
 * Adyen Checkout API
 *
 * The version of the OpenAPI document: 72
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Adyen.Core;
using Adyen.Core.Converters;
using Adyen.Checkout.Client;

namespace Adyen.Checkout.Models
{
    /// <summary>
    /// CheckoutRedirectAction.
    /// </summary>
    [JsonConverter(typeof(CheckoutRedirectActionJsonConverter))]
    public partial class CheckoutRedirectAction
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckoutRedirectAction" /> class.
        /// </summary>
        public CheckoutRedirectAction()
        {
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// **redirect**
        /// </summary>
        /// <value>**redirect**</value>
        [JsonConverter(typeof(TypeEnumJsonConverter))]
        public class TypeEnum : IEnum
        {
            /// <summary>
            /// Returns the value of the TypeEnum.
            /// </summary>
            public string? Value { get; set; }

            /// <summary>
            /// TypeEnum.Redirect - redirect
            /// </summary>
            public static readonly TypeEnum Redirect = new("redirect");
        
            private TypeEnum(string? value)
            {
                Value = value;
            }

            /// <summary>
            /// Converts a string to a <see cref="TypeEnum"/> implicitly.
            /// </summary>
            /// <param name="value">The string value to convert. Defaults to null.</param>
            /// <returns>A new <see cref="TypeEnum"/> instance initialized with the string value.</returns>
            public static implicit operator TypeEnum?(string? value) => value == null ? null : new TypeEnum(value);
    
            /// <summary>
            /// Converts a <see cref="TypeEnum"/> instance to a string implicitly.
            /// </summary>
            /// <param name="option">The <see cref="TypeEnum"/> instance. Default to null.</param>
            /// <returns>String value of the <see cref="TypeEnum"/> instance.</returns>
            public static implicit operator string?(TypeEnum? option) => option?.Value;
        
            /// <summary>
            /// Compares two <see cref="TypeEnum"/> instances for equality.
            /// </summary>
            public static bool operator ==(TypeEnum? left, TypeEnum? right) => string.Equals(left?.Value, right?.Value, StringComparison.OrdinalIgnoreCase);

            /// <summary>
            /// Compares two <see cref="TypeEnum"/> instances for inequality.
            /// </summary>
            public static bool operator !=(TypeEnum? left, TypeEnum? right) => !string.Equals(left?.Value, right?.Value, StringComparison.OrdinalIgnoreCase);

            /// <summary>
            /// Returns true if the given object is equal to this <see cref="TypeEnum"/> instance.
            /// </summary>
            public override bool Equals(object? obj) => obj is TypeEnum other && string.Equals(Value, other.Value, StringComparison.OrdinalIgnoreCase);

            /// <summary>
            /// Returns a hash code for this <see cref="TypeEnum"/> instance.
            /// </summary>
            public override int GetHashCode() => Value?.GetHashCode() ?? 0;

            /// <summary>
            /// Returns the string value of the <see cref="TypeEnum"/> instance.
            /// </summary>
            public override string ToString() => Value ?? string.Empty;
        
            /// <summary>
            /// Returns a <see cref="TypeEnum?"/>.
            /// </summary>
            /// <param name="value"></param>
            /// <returns><see cref="TypeEnum"/> or null.</returns>
            public static TypeEnum? FromStringOrDefault(string value)
            {
                return value switch {
                    "redirect" => TypeEnum.Redirect,
                    _ => null,
                };
            }
    
            /// <summary>
            /// Converts the <see cref="TypeEnum"/> to the json value.
            /// </summary>
            /// <param name="value"><see cref="TypeEnum"/></param>
            /// <returns>String value of the enum.</returns>
            public static string? ToJsonValue(TypeEnum? value)
            {
                if (value == null)
                    return null;
            
                if (value == TypeEnum.Redirect)
                    return "redirect";
                
                return value.Value;
            }
            
            /// <summary>
            /// JsonConverter for writing TypeEnum.               
            /// </summary>
            public class TypeEnumJsonConverter : JsonConverter<TypeEnum>
            {
                /// <summary>
                /// Deserializes a <see cref="TypeEnum"/> from JSON.
                /// </summary>
                public override TypeEnum? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions jsonOptions)
                {
                    string value = reader.GetString();
                    return value == null ? null : TypeEnum.FromStringOrDefault(value) ?? new TypeEnum(value);
                }

                /// <summary>
                /// Serializes a <see cref="TypeEnum"/> to JSON.
                /// </summary>
                public override void Write(Utf8JsonWriter writer, TypeEnum value, JsonSerializerOptions jsonOptions)
                {
                    writer.WriteStringValue(TypeEnum.ToJsonValue(value));
                }
            }
        }

        /// <summary>
        /// **redirect**
        /// </summary>
        /// <value>**redirect**</value>
        [JsonPropertyName("type")]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// This is used to track if an optional field is set. If set, <see cref="Data"/> will be populated.
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, string>?> _DataOption { get; private set; }

        /// <summary>
        /// When the redirect URL must be accessed via POST, use this data to post to the redirect URL.
        /// </summary>
        /// <value>When the redirect URL must be accessed via POST, use this data to post to the redirect URL.</value>
        [JsonPropertyName("data")]
        public Dictionary<string, string>? Data { get { return this._DataOption; } set { this._DataOption = new(value); } }

        /// <summary>
        /// This is used to track if an optional field is set. If set, <see cref="Method"/> will be populated.
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> _MethodOption { get; private set; }

        /// <summary>
        /// Specifies the HTTP method, for example GET or POST.
        /// </summary>
        /// <value>Specifies the HTTP method, for example GET or POST.</value>
        [JsonPropertyName("method")]
        public string? Method { get { return this._MethodOption; } set { this._MethodOption = new(value); } }

        /// <summary>
        /// This is used to track if an optional field is set. If set, <see cref="PaymentMethodType"/> will be populated.
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> _PaymentMethodTypeOption { get; private set; }

        /// <summary>
        /// Specifies the payment method.
        /// </summary>
        /// <value>Specifies the payment method.</value>
        [JsonPropertyName("paymentMethodType")]
        public string? PaymentMethodType { get { return this._PaymentMethodTypeOption; } set { this._PaymentMethodTypeOption = new(value); } }

        /// <summary>
        /// This is used to track if an optional field is set. If set, <see cref="Url"/> will be populated.
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> _UrlOption { get; private set; }

        /// <summary>
        /// Specifies the URL to redirect to.
        /// </summary>
        /// <value>Specifies the URL to redirect to.</value>
        [JsonPropertyName("url")]
        public string? Url { get { return this._UrlOption; } set { this._UrlOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CheckoutRedirectAction {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Method: ").Append(Method).Append("\n");
            sb.Append("  PaymentMethodType: ").Append(PaymentMethodType).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CheckoutRedirectAction" />
    /// </summary>
    public class CheckoutRedirectActionJsonConverter : JsonConverter<CheckoutRedirectAction>
    {
        /// <summary>
        /// Deserializes json to <see cref="CheckoutRedirectAction"/>.
        /// </summary>
        /// <param name="utf8JsonReader"><see cref="Utf8JsonReader"/>.</param>
        /// <param name="typeToConvert"><see cref="Type"/>.</param>
        /// <param name="jsonSerializerOptions">The <see cref="JsonSerializerOptions"/>, initialized from <see cref="HostConfiguration"/>.</param>
        /// <returns><see cref="CheckoutRedirectAction"/>.</returns>
        /// <exception cref="JsonException"></exception>
        public override CheckoutRedirectAction Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<CheckoutRedirectAction.TypeEnum?> type = default;
            Option<Dictionary<string, string>?> data = default;
            Option<string?> method = default;
            Option<string?> paymentMethodType = default;
            Option<string?> url = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? jsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (jsonPropertyName)
                    {
                        case "type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            type = new Option<CheckoutRedirectAction.TypeEnum?>(CheckoutRedirectAction.TypeEnum.FromStringOrDefault(typeRawValue) ?? (CheckoutRedirectAction.TypeEnum)typeRawValue);
                            break;
                        case "data":
                            data = new Option<Dictionary<string, string>?>(JsonSerializer.Deserialize<Dictionary<string, string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "method":
                            method = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "paymentMethodType":
                            paymentMethodType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "url":
                            url = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }
            

            var checkoutRedirectAction = new CheckoutRedirectAction();
            if (type.IsSet)
                checkoutRedirectAction.Type = type.Value!;
            if (data.IsSet)
                checkoutRedirectAction.Data = data.Value;
            if (method.IsSet)
                checkoutRedirectAction.Method = method.Value;
            if (paymentMethodType.IsSet)
                checkoutRedirectAction.PaymentMethodType = paymentMethodType.Value;
            if (url.IsSet)
                checkoutRedirectAction.Url = url.Value;
            return checkoutRedirectAction;
        }

        /// <summary>
        /// Serializes a <see cref="CheckoutRedirectAction"/>.
        /// </summary>
        /// <param name="writer"><see cref="Utf8JsonWriter"/></param>
        /// <param name="checkoutRedirectAction"></param>
        /// <param name="jsonSerializerOptions"><see cref="JsonSerializerOptions"/></param>
        public override void Write(Utf8JsonWriter writer, CheckoutRedirectAction checkoutRedirectAction, JsonSerializerOptions jsonSerializerOptions)
        {
            
            writer.WriteStartObject();
            
            WriteProperties(writer, checkoutRedirectAction, jsonSerializerOptions);
            
            writer.WriteEndObject();
            
        }

        /// <summary>
        /// Serializes the properties of <see cref="CheckoutRedirectAction"/>.
        /// </summary>
        /// <param name="writer"><see cref="Utf8JsonWriter"/></param>
        /// <param name="checkoutRedirectAction"></param>
        /// <param name="jsonSerializerOptions"><see cref="JsonSerializerOptions"/></param>
        public void WriteProperties(Utf8JsonWriter writer, CheckoutRedirectAction checkoutRedirectAction, JsonSerializerOptions jsonSerializerOptions)
        {
            
            if (checkoutRedirectAction.Type != null) 
            {
                string? typeRawValue = CheckoutRedirectAction.TypeEnum.ToJsonValue(checkoutRedirectAction.Type);
                writer.WriteString("type", typeRawValue);
            }
            
            if (checkoutRedirectAction._DataOption.IsSet)
            {
                writer.WritePropertyName("data");
                JsonSerializer.Serialize(writer, checkoutRedirectAction.Data, jsonSerializerOptions);
            }
            if (checkoutRedirectAction._MethodOption.IsSet)
                if (checkoutRedirectAction.Method != null)
                    writer.WriteString("method", checkoutRedirectAction.Method);

            if (checkoutRedirectAction._PaymentMethodTypeOption.IsSet)
                if (checkoutRedirectAction.PaymentMethodType != null)
                    writer.WriteString("paymentMethodType", checkoutRedirectAction.PaymentMethodType);

            if (checkoutRedirectAction._UrlOption.IsSet)
                if (checkoutRedirectAction.Url != null)
                    writer.WriteString("url", checkoutRedirectAction.Url);
        }
    }
}
