// <auto-generated>
/*
 * Adyen Checkout API
 *
 * The version of the OpenAPI document: 72
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Adyen.Core;
using Adyen.Core.Converters;
using Adyen.Checkout.Client;

namespace Adyen.Checkout.Models
{
    /// <summary>
    /// EncryptedOrderData.
    /// </summary>
    [JsonConverter(typeof(EncryptedOrderDataJsonConverter))]
    public partial class EncryptedOrderData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EncryptedOrderData" /> class.
        /// </summary>
        public EncryptedOrderData()
        {
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The encrypted order data.
        /// </summary>
        /// <value>The encrypted order data.</value>
        [JsonPropertyName("orderData")]
        public string? OrderData { get; set; }

        /// <summary>
        /// The &#x60;pspReference&#x60; that belongs to the order.
        /// </summary>
        /// <value>The `pspReference` that belongs to the order.</value>
        [JsonPropertyName("pspReference")]
        public string? PspReference { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EncryptedOrderData {\n");
            sb.Append("  OrderData: ").Append(OrderData).Append("\n");
            sb.Append("  PspReference: ").Append(PspReference).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EncryptedOrderData" />
    /// </summary>
    public class EncryptedOrderDataJsonConverter : JsonConverter<EncryptedOrderData>
    {
        /// <summary>
        /// Deserializes json to <see cref="EncryptedOrderData"/>.
        /// </summary>
        /// <param name="utf8JsonReader"><see cref="Utf8JsonReader"/>.</param>
        /// <param name="typeToConvert"><see cref="Type"/>.</param>
        /// <param name="jsonSerializerOptions">The <see cref="JsonSerializerOptions"/>, initialized from <see cref="HostConfiguration"/>.</param>
        /// <returns><see cref="EncryptedOrderData"/>.</returns>
        /// <exception cref="JsonException"></exception>
        public override EncryptedOrderData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> orderData = default;
            Option<string?> pspReference = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? jsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (jsonPropertyName)
                    {
                        case "orderData":
                            orderData = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "pspReference":
                            pspReference = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }
            

            var encryptedOrderData = new EncryptedOrderData();
            if (orderData.IsSet)
                encryptedOrderData.OrderData = orderData.Value!;
            if (pspReference.IsSet)
                encryptedOrderData.PspReference = pspReference.Value!;
            return encryptedOrderData;
        }

        /// <summary>
        /// Serializes a <see cref="EncryptedOrderData"/>.
        /// </summary>
        /// <param name="writer"><see cref="Utf8JsonWriter"/></param>
        /// <param name="encryptedOrderData"></param>
        /// <param name="jsonSerializerOptions"><see cref="JsonSerializerOptions"/></param>
        public override void Write(Utf8JsonWriter writer, EncryptedOrderData encryptedOrderData, JsonSerializerOptions jsonSerializerOptions)
        {
            
            writer.WriteStartObject();
            
            WriteProperties(writer, encryptedOrderData, jsonSerializerOptions);
            
            writer.WriteEndObject();
            
        }

        /// <summary>
        /// Serializes the properties of <see cref="EncryptedOrderData"/>.
        /// </summary>
        /// <param name="writer"><see cref="Utf8JsonWriter"/></param>
        /// <param name="encryptedOrderData"></param>
        /// <param name="jsonSerializerOptions"><see cref="JsonSerializerOptions"/></param>
        public void WriteProperties(Utf8JsonWriter writer, EncryptedOrderData encryptedOrderData, JsonSerializerOptions jsonSerializerOptions)
        {
            
            if (encryptedOrderData.OrderData != null)
                writer.WriteString("orderData", encryptedOrderData.OrderData);

            if (encryptedOrderData.PspReference != null)
                writer.WriteString("pspReference", encryptedOrderData.PspReference);
        }
    }
}
